export type EvidenceLevel = "Forte" | "Moderada" | "Limitada" | "Editorial";

export const startingLines = [
  { title: "Movimento desde cedo", status: "Ampliar", text: "Brincar, correr, saltar, lançar, equilibrar, nadar e explorar o corpo com prazer e segurança." },
  { title: "Contato com o atletismo", status: "Oferecer", text: "Conhecer corridas, saltos, lançamentos, circuitos, ritmos e competições adaptadas." },
  { title: "Especialização no fundo", status: "Não antecipar", text: "Treinar predominantemente resistência, aumentar volume e reduzir variedade exige maturidade e cautela." }
] as const;

export const countries = [
  { id:"quenia", country:"Quênia", mechanism:"Cultura regional, movimento cotidiano e redes de treinamento", school:"A escola e o deslocamento aparecem em trajetórias de parte dos atletas.", pathway:"Referências locais, clubes, campos e perspectiva econômica tornam o caminho visível.", opportunity:"Criar movimento cotidiano, referências e continuidade comunitária.", limitation:"Evidência observacional, regional e retrospectiva; associação não prova causa.", avoid:"Romantizar pobreza, corrida descalça, origem étnica ou deslocamentos inseguros.", level:"Moderada" as EvidenceLevel },
  { id:"etiopia", country:"Etiópia", mechanism:"Geografia concentrada, escolas, academias e centros juvenis", school:"Ambientes escolares ajudam a revelar interesse e conectá-lo a redes locais.", pathway:"Talento percebido encontra academias, técnicos e centros de desenvolvimento.", opportunity:"Construir redes capazes de observar e acompanhar sem sentenciar.", limitation:"Atletas de elite não representam toda a infância etíope.", avoid:"Transformar altitude, origem ou dificuldade econômica em fórmula de campeão.", level:"Limitada" as EvidenceLevel },
  { id:"uganda", country:"Uganda", mechanism:"Integração crescente entre escola, federação e programas de atletismo", school:"A escola primária pode massificar o primeiro contato.", pathway:"Programas federativos e comunitários procuram ligar descoberta e continuidade.", opportunity:"Usar a capilaridade escolar como porta aberta para experimentar.", limitation:"Estrutura e acesso permanecem desiguais entre territórios.", avoid:"Tratar iniciativas recentes como sistema universal já consolidado.", level:"Limitada" as EvidenceLevel },
  { id:"japao", country:"Japão", mechanism:"Clubes escolares, calendário, campeonatos e cultura do ekiden", school:"A escola cria rotina, pertencimento, identidade coletiva e continuidade.", pathway:"Clubes e competições tornam as próximas etapas reconhecíveis.", opportunity:"Calendário, pertencimento e conexão institucional.", limitation:"Sobrecarga de professores, excesso de carga e desigualdades motivam reformas.", avoid:"Copiar frequência e pressão sem a rede de proteção correspondente.", level:"Moderada" as EvidenceLevel },
  { id:"eua", country:"Estados Unidos", mechanism:"Escola, cross country, track and field, universidade e bolsas", school:"Temporadas escolares organizam participação e progressão competitiva.", pathway:"O jovem visualiza etapas futuras, embora somente uma minoria chegue à NCAA.", opportunity:"Dar visibilidade a transições e combinar esporte e educação.", limitation:"Acesso é desigual e bolsas podem ser parciais ou inexistentes.", avoid:"Vender universidade ou bolsa como consequência automática de bons tempos.", level:"Forte" as EvidenceLevel },
  { id:"noruega", country:"Noruega", mechanism:"Participação ampla, direitos, variedade e competição regulada", school:"Esporte comunitário e direitos infantis priorizam escolha, prazer e segurança.", pathway:"A competição existe, mas progride com limites de ranking e viagem.", opportunity:"Colocar permanência, autonomia e prazer antes da seleção.", limitation:"Também há abandono na adolescência; o modelo não é específico do fundo.", avoid:"Dizer que não existe competição infantil ou copiar regras fora do contexto.", level:"Forte" as EvidenceLevel },
  { id:"brasil", country:"Brasil", mechanism:"Educação Física, federações, clubes e projetos ainda fragmentados", school:"A disciplina é obrigatória, mas infraestrutura e acesso variam muito.", pathway:"Há categorias e competições; as transições entre escola, projeto e clube falham.", opportunity:"Conectar as peças existentes em uma rede territorial contínua.", limitation:"Dados de acesso e idade de início não são equivalentes entre regiões.", avoid:"Afirmar que nada existe ou selecionar crianças apenas pelo tempo atual.", level:"Forte" as EvidenceLevel }
] as const;

export const evidenceClaims = [
  { claim:"Crianças se beneficiam de repertório motor e ambientes esportivos adequados ao desenvolvimento.", interpretation:"Acesso precoce deve significar variedade, prazer, aprendizagem e proteção.", level:"Forte" as EvidenceLevel },
  { claim:"Resultados juvenis têm valor prognóstico, mas não garantem excelência adulta.", interpretation:"Apenas cerca de um quinto dos melhores Sub-18 estudados chegou ao grupo de elite adulto.", level:"Moderada" as EvidenceLevel },
  { claim:"Atletas adultos de nível mundial tendem a relatar mais experiências multiesportivas e progressão gradual.", interpretation:"Especialização precoce não é requisito universal para chegar ao topo.", level:"Moderada" as EvidenceLevel },
  { claim:"Deslocamento ativo aparece com frequência em estudos de corredores do Leste Africano.", interpretation:"A associação é relevante, porém retrospectiva e incapaz de estabelecer causalidade.", level:"Limitada" as EvidenceLevel },
  { claim:"O Brasil precisa conectar escola, comunidade, técnicos, clubes e competições.", interpretation:"É uma síntese editorial baseada nas lacunas observadas, não um efeito causal já comprovado.", level:"Editorial" as EvidenceLevel }
] as const;

export const ecosystemNodes = ["Movimento cotidiano", "Escola", "Família", "Projeto local", "Treinador", "Clube", "Competição adequada", "Saúde e proteção", "Educação", "Transição adulta"] as const;

export const lateStartReferences = [
  {axis:"Desenvolvimento",title:"Kids’ Athletics",source:"World Athletics",year:"2026",summary:"Programa de quatro a 14 anos baseado em correr, saltar, lançar, inclusão e diversão.",limitation:"Contato com atletismo não equivale a especialização no fundo.",url:"https://worldathletics.org/kids-athletics"},
  {axis:"Proteção",title:"IOC consensus statement on elite youth athletes",source:"Comitê Olímpico Internacional",year:"2024",summary:"Defende desenvolvimento holístico, saúde, direitos e sustentabilidade no esporte juvenil.",limitation:"Princípios amplos exigem adaptação territorial.",url:"https://bjsm.bmj.com/content/58/17/946"},
  {axis:"Especialização",title:"What makes a champion?",source:"Güllich, Macnamara e Hambrick",year:"2022",summary:"Distingue sucesso juvenil de excelência adulta e destaca experiências multiesportivas.",limitation:"A síntese reúne modalidades e desenhos heterogêneos.",url:"https://journals.sagepub.com/doi/abs/10.1177/1745691620974772"},
  {axis:"Transição",title:"Performance pathways in elite middle- and long-distance athletes",source:"Barth e colaboradores",year:"2024",summary:"Mostra baixa permanência dos melhores Sub-18 entre os melhores adultos.",limitation:"Ranking juvenil tem valor estatístico, não destino individual.",url:"https://pubmed.ncbi.nlm.nih.gov/38821815/"},
  {axis:"Quênia",title:"Demographic characteristics of elite Kenyan endurance runners",source:"Onywera e colaboradores",year:"2006",summary:"Descreve origem e deslocamento escolar relatado por corredores quenianos.",limitation:"Retrospectivo; não demonstra que correr à escola cause excelência.",url:"https://pubmed.ncbi.nlm.nih.gov/16492605/"},
  {axis:"Leste Africano",title:"Kenyan and Ethiopian distance running success",source:"Wilber e Pitsiladis",year:"2012",summary:"Revisa fatores fisiológicos, ambientais, culturais e de treinamento.",limitation:"Nenhuma característica isolada explica o domínio regional.",url:"https://pubmed.ncbi.nlm.nih.gov/22634972/"},
  {axis:"Etiópia",title:"Demographic characteristics of elite Ethiopian endurance runners",source:"Scott e colaboradores",year:"2003",summary:"Analisa origem geográfica e deslocamento em atletas etíopes de elite.",limitation:"Não representa a infância etíope em geral.",url:"https://pubmed.ncbi.nlm.nih.gov/14523311/"},
  {axis:"Uganda",title:"Athletics promotion through schools in Uganda",source:"World Athletics",year:"2023",summary:"Relata iniciativas de promoção do atletismo ligadas a escolas e federação.",limitation:"Relato institucional não mede impacto longitudinal.",url:"https://worldathletics.org/news/news/joint-actions-in-uganda-for-athletics-promoti"},
  {axis:"Japão",title:"Sports participation and school clubs in Japan",source:"Sasakawa Sports Foundation",year:"2024",summary:"Apresenta a centralidade e as mudanças dos clubes esportivos escolares.",limitation:"Participação nacional não descreve cada escola ou atleta.",url:"https://www.ssf.or.jp/en/features/japans_data_plus_sports/e0001.html"},
  {axis:"Estados Unidos",title:"Probability of competing beyond high school",source:"NCAA",year:"2025",summary:"Dimensiona a pequena parcela de atletas escolares que avança ao esporte universitário.",limitation:"Probabilidades agregadas não garantem acesso ou bolsa.",url:"https://www.ncaa.org/student-athletes/probability-of-competing-beyond-high-school/"},
  {axis:"Noruega",title:"Children’s Rights in Sports",source:"Norwegian Olympic and Paralympic Committee",year:"2026",summary:"Define direitos de participação, escolha, segurança e competição progressiva.",limitation:"O modelo é multiesportivo e depende da organização comunitária norueguesa.",url:"https://www.idrettsforbundet.no/english/childrens-rights-in-sports/"},
  {axis:"Brasil",title:"Educação Física: obrigatoriedade da disciplina",source:"Conselho Nacional de Educação",year:"2026",summary:"Reúne as normas brasileiras sobre Educação Física escolar obrigatória.",limitation:"Obrigatoriedade legal não assegura qualidade ou acesso equivalentes.",url:"https://www.gov.br/mec/pt-br/cne/normas-classificadas-por-assunto/educacao-fisica-obrigatoriedade-da-disciplina"},
  {axis:"Brasil",title:"Norma 12: categorias oficiais por faixa etária",source:"CBAt",year:"2025",summary:"Organiza as categorias oficiais do atletismo brasileiro.",limitation:"Categorias competitivas não comprovam uma rede contínua de formação.",url:"https://cbat.org.br/noticia/107237/cbat-atualiza-norma-12-sobre-categorias-oficiais-do-atletismo-por-faixas-etarias"}
] as const;

export const lateStartFaq = [
  ["O Brasil realmente começa tarde no fundismo?","Não existe uma idade nacional única e comparável. O problema mais defensável é a chegada tardia e desigual a caminhos contínuos de movimento, atletismo e orientação."],
  ["Existe uma idade ideal para começar?","Não há idade universal. Movimento e repertório podem começar cedo; especialização, carga e metas precisam respeitar desenvolvimento, interesse e contexto."],
  ["Começar cedo significa treinar mais?","Não. Significa ter mais oportunidades de brincar, aprender habilidades e conhecer o atletismo sem antecipar volume."],
  ["Crianças podem competir?","Sim, quando formato, distância, ambiente, regras e expectativas são adequados à idade e centrados na criança."],
  ["Crianças devem correr provas longas?","Distâncias e cargas precisam ser progressivas e orientadas. A infância não deve reproduzir o treinamento adulto."],
  ["Por que o repertório motor importa?","Variedade amplia competência, prazer, adaptação e opções futuras, além de evitar que um resultado precoce defina a trajetória."],
  ["Especialização precoce produz melhores adultos?","Não de forma universal. Ela pode favorecer resultados juvenis, enquanto trajetórias adultas excelentes frequentemente incluem variedade e progressão gradual."],
  ["Um campeão Sub-14 será campeão adulto?","Não. Crescimento, maturação, saúde, acesso, motivação e oportunidades mudam profundamente a trajetória."],
  ["Começar aos 14 é tarde demais?","Não. Portas de entrada tardias precisam permanecer abertas e podem produzir trajetórias excelentes."],
  ["Correr para a escola explica o sucesso africano?","Não. É uma associação observada em grupos específicos e integra um conjunto muito maior de fatores."],
  ["Qual é o papel da altitude?","É um componente ambiental possível, não uma explicação isolada para campeões ou sistemas nacionais."],
  ["Todo atleta americano recebe bolsa?","Não. Apenas uma minoria avança à NCAA, e bolsas podem ser parciais ou inexistentes."],
  ["Na Noruega existe competição infantil?","Sim. Ela é regulada e progressiva, com direitos, limites e prioridade à participação."],
  ["O Brasil possui atletismo de base?","Sim. Existem categorias, competições, escolas, clubes e projetos; o desafio é distribuir e conectar essas peças."],
  ["O que a escola deve fazer?","Ampliar acesso, repertório e pertencimento — não sentenciar quem tem ou não talento."],
  ["Como o Onze Futuro responde?","Como projeto piloto de acompanhamento profundo, proteção e aprendizagem. Não é modelo cientificamente comprovado nem promessa de alto rendimento."],
  ["Cinco atletas validam um modelo?","Não. Uma turma pequena permite avaliar viabilidade e acompanhar casos, sem generalizar resultados."],
  ["O projeto cria score de talento?","Não. Tempos e medidas são contextualizados; não há previsão automatizada de carreira ou ranking biológico."],
  ["Como proteger dados infantis?","Com minimização, finalidade clara, autorização adequada, acesso restrito e ausência de decisões automatizadas."],
  ["Onde consultar as fontes?","Na biblioteca desta página, que informa interpretação, limitação e data de revisão de cada referência."]
] as const;
