export const developmentFactors = [
  { title: "Crescimento", text: "Mudanças de altura, massa e proporções corporais acontecem em ritmos individuais." },
  { title: "Maturação", text: "É o caminho biológico até o estado adulto. O momento e a velocidade desse processo variam." },
  { title: "Experiência", text: "Tempo de prática, repertório motor e qualidade do treinamento também influenciam o resultado." },
  { title: "Contexto", text: "Sono, alimentação, segurança, escola, família e acesso a oportunidades fazem parte da trajetória." }
] as const;

export const manifesto = [
  "não definir talento por uma única marca",
  "não publicar rankings de maturação biológica",
  "não comparar corpos de crianças",
  "não utilizar IA para realizar diagnóstico médico",
  "não transformar estimativas em certezas",
  "não excluir atletas automaticamente por algoritmos",
  "não expor informações sensíveis",
  "respeitar a decisão e a autorização dos responsáveis",
  "priorizar o melhor interesse da criança",
  "preservar saúde, educação e bem-estar",
  "comunicar limitações dos dados",
  "manter supervisão humana"
] as const;

export const faqs = [
  ["O que é idade biológica?", "É uma forma de descrever o estágio de desenvolvimento do organismo. Ela não é um número exato, não substitui avaliação clínica e deve ser interpretada por profissionais qualificados."],
  ["Idade biológica e idade cronológica são a mesma coisa?", "Não. A idade cronológica conta o tempo desde o nascimento; o desenvolvimento biológico observa processos de crescimento e maturação, que variam entre pessoas da mesma idade."],
  ["Duas crianças da mesma idade podem estar em fases diferentes?", "Sim. Diferenças de crescimento, coordenação, força, experiência e momento maturacional são esperadas e podem influenciar temporariamente o desempenho."],
  ["Uma criança maior é necessariamente mais talentosa?", "Não. Vantagens físicas do momento podem ser transitórias. Talento envolve múltiplas dimensões e precisa ser acompanhado ao longo do tempo."],
  ["Uma criança menor terá mais potencial no futuro?", "Também não é possível afirmar isso. Tamanho atual ou ritmo de maturação não permitem prever, isoladamente, uma carreira esportiva."],
  ["A maturação pode influenciar resultados esportivos?", "Pode influenciar força, velocidade, coordenação e resposta ao treino, mas não age sozinha e não determina o potencial definitivo."],
  ["É possível determinar exatamente a idade biológica?", "Existem métodos clínicos e estimativas não invasivas, todos com limites. Nenhuma estimativa pública desta página produz diagnóstico."],
  ["O que é pico de velocidade de crescimento?", "É o período de maior velocidade de crescimento em estatura durante a adolescência. Seu momento varia e pode exigir atenção à carga e à coordenação."],
  ["O que é efeito da idade relativa?", "É a vantagem ou desvantagem associada ao mês de nascimento dentro de uma categoria anual. Quem nasceu no início do corte pode ter meses adicionais de desenvolvimento."],
  ["O que é bio-banding?", "É um recurso que, em alguns contextos, agrupa jovens por características de maturação em vez de usar apenas a idade. É complementar, não uma solução universal."],
  ["O 11RUN separa atletas por maturação?", "Não como regra automática. Qualquer uso futuro desse recurso exigiria objetivo claro, supervisão profissional, proteção de dados e avaliação humana."],
  ["O 11RUN usa inteligência artificial para selecionar crianças?", "Não. IA não deve diagnosticar, atribuir nota de talento, prever carreira ou excluir atletas. Decisões esportivas relevantes continuam humanas."],
  ["Dados de crescimento serão divulgados?", "Não. Dados de saúde e desenvolvimento de menores exigem alto cuidado e não devem aparecer em rankings ou perfis públicos."],
  ["A página substitui avaliação médica?", "Não. Este conteúdo é educativo e não oferece diagnóstico, prescrição de treino ou orientação médica individual."],
  ["Como os pais podem acompanhar o desenvolvimento?", "Observando a trajetória, mantendo diálogo com a criança e os profissionais e preservando sono, alimentação, estudo, lazer e saúde."],
  ["Como treinadores devem interpretar rankings infantis?", "Como uma fotografia contextual do desempenho atual, nunca como veredito de potencial. Histórico, idade relativa, experiência e desenvolvimento importam."],
  ["Um resultado ruim nesta fase significa falta de talento?", "Não. Uma marca isolada pode refletir muitos fatores temporários. Evolução consistente e acompanhamento longitudinal oferecem mais contexto."],
  ["Um resultado muito forte garante sucesso no adulto?", "Não. Desempenho precoce não garante carreira futura. Desenvolvimento sustentável depende de saúde, adaptação, ambiente, motivação e continuidade."]
] as const;

export const scientificReferences = [
  { authors: "Malina, Rogol, Cumming e colaboradores", title: "Maturação biológica de jovens atletas: avaliação e implicações", originalTitle: "Biological maturation of youth athletes: assessment and implications", year: "2015", publication: "British Journal of Sports Medicine", category: "Maturação", summary: "Apresenta métodos de avaliação e implicações da maturação para jovens atletas.", translatedSummary: "A busca por talentos no esporte juvenil frequentemente favorece atletas mais adiantados no processo de maturação, sobretudo durante a puberdade e o estirão de crescimento. A publicação descreve métodos usados para avaliar o estágio maturacional, como idade esquelética e características sexuais secundárias, além de estimativas não invasivas baseadas em medidas corporais. Os autores destacam que os métodos antropométricos ainda precisam de validação adicional em atletas. O desenvolvimento do talento acontece sobre uma base em mudança contínua, na qual crescimento físico, maturação biológica e desenvolvimento comportamental interagem com as exigências do esporte e com a influência de treinadores, gestores e responsáveis.", keyPoint: "Maturação deve contextualizar a avaliação; não pode funcionar como rótulo ou critério isolado de seleção.", limitation: "Métodos estimativos possuem margem de erro e não substituem avaliação profissional individualizada.", url: "https://pubmed.ncbi.nlm.nih.gov/26084525/" },
  { authors: "Bergeron e colaboradores", title: "Consenso do COI sobre jovens atletas de elite nos Jogos Olímpicos", originalTitle: "IOC consensus statement on elite youth athletes competing at the Olympic Games: essentials to a healthy, safe and sustainable paradigm", year: "2024", publication: "British Journal of Sports Medicine", category: "Proteção", summary: "Propõe um desenvolvimento individualizado, saudável, seguro e centrado na criança.", translatedSummary: "O consenso reconhece a adolescência como uma fase dinâmica, marcada por mudanças físicas, fisiológicas, psicológicas e sociais que não acontecem ao mesmo tempo para todos. Propõe um modelo centrado no jovem atleta, com caminhos individualizados e sustentáveis para treinamento e competição internacional. Saúde, maturação, segurança, nutrição, bem-estar mental, educação, relações de apoio e proteção de direitos devem ser considerados em conjunto. O documento também recomenda formação contínua de treinadores, estratégias de safeguarding e formatos competitivos flexíveis que acolham atletas com maturação precoce ou tardia.", keyPoint: "Desempenho esportivo e proteção integral precisam avançar juntos em uma estratégia de longo prazo.", limitation: "O consenso reúne evidências e recomendações gerais; sua aplicação exige adaptação ao esporte, ao contexto e ao atleta.", url: "https://bjsm.bmj.com/content/58/17/946" },
  { authors: "Hagiwara e colaboradores", title: "Trajetórias da aptidão física conforme a maturação de jovens talentos", originalTitle: "Maturity-specific trajectories of physical fitness in talented youth athletes: a longitudinal study of Japanese local talent identification and development programme", year: "2026", publication: "Frontiers in Sports and Active Living", category: "Talento", summary: "Estudo longitudinal japonês que reforça a leitura de trajetórias e múltiplas dimensões físicas.", translatedSummary: "O estudo acompanhou jovens participantes de um programa japonês de identificação e desenvolvimento de talentos para observar como diferentes componentes da aptidão física evoluem em relação ao pico de velocidade de crescimento. Os resultados indicam que as trajetórias não são uniformes: capacidades físicas e motoras podem mudar de maneiras distintas conforme o momento maturacional. A leitura longitudinal oferece mais informação do que uma avaliação isolada e ajuda profissionais a reconhecer que o desempenho atual pode refletir uma fase transitória do desenvolvimento.", keyPoint: "Talento deve ser acompanhado por múltiplas medidas e ao longo do tempo, não definido por uma fotografia única.", limitation: "Os achados pertencem a um programa e a uma amostra específicos; não devem ser generalizados automaticamente para todas as populações.", url: "https://www.frontiersin.org/journals/sports-and-active-living/articles/10.3389/fspor.2026.1821744/full" },
  { authors: "Parry e colaboradores", title: "Relações entre crescimento, maturação e lesões em jovens atletas de elite", originalTitle: "Associations between growth, maturation and injury in youth athletes engaged in elite pathways: a scoping review", year: "2024", publication: "British Journal of Sports Medicine", category: "Lesões", summary: "Revisão sobre relações entre crescimento, maturação e risco ou carga de lesões.", translatedSummary: "A revisão analisou 30 estudos sobre crescimento, maturação e lesões em jovens inseridos em trajetórias de elite. Em geral, incidência e carga de lesões aumentaram em alguns estágios maturacionais, enquanto lesões relacionadas ao crescimento apareceram com mais frequência durante o estirão adolescente. Crescimento mais rápido em estatura e nos membros inferiores também foi associado a maior incidência ou carga de lesões. Contudo, as relações variaram conforme o tipo de lesão, e o momento da maturação não apresentou um padrão único e consistente.", keyPoint: "Monitorar crescimento pode apoiar prevenção e ajuste de cargas, sempre com interpretação clínica e esportiva.", limitation: "Os estudos são heterogêneos e há pouca evidência exclusiva com atletas do sexo feminino e em maior diversidade de esportes.", url: "https://pubmed.ncbi.nlm.nih.gov/39209526/" },
  { authors: "Cumming e colaboradores", title: "Bio-banding no esporte: competição, identificação de talentos e preparação física", originalTitle: "Bio-banding in Sport: Applications to Competition, Talent Identification, and Strength and Conditioning of Youth Athletes", year: "2017", publication: "Strength and Conditioning Journal", category: "Bio-banding", summary: "Discute aplicações e limites do agrupamento por maturação no esporte juvenil.", translatedSummary: "A publicação apresenta o bio-banding como uma estratégia complementar para agrupar jovens de acordo com características de maturação, em vez de considerar somente a idade cronológica. A abordagem pode criar experiências competitivas e de treinamento diferentes, reduzir algumas vantagens físicas temporárias e oferecer novas oportunidades de observação do talento. Também pode apoiar decisões de preparação física mais adequadas ao estágio de desenvolvimento. Os autores não tratam o método como substituto permanente das categorias por idade, mas como uma ferramenta que deve ser combinada com outras formas de avaliação.", keyPoint: "Bio-banding amplia o contexto de observação, mas não determina talento nem elimina a necessidade de julgamento profissional.", limitation: "Estimativas de maturação e critérios de agrupamento possuem limites; efeitos sociais, psicológicos e práticos também devem ser considerados.", url: "https://doi.org/10.1519/SSC.0000000000000281" },
  { authors: "World Athletics", title: "Crescimento e desenvolvimento", originalTitle: "Growth and Development", year: "Material educacional", publication: "World Athletics", category: "Crescimento", summary: "Conteúdo institucional sobre crescimento, desenvolvimento e treinamento de jovens atletas.", translatedSummary: "O material educacional organiza características do desenvolvimento motor, da aprendizagem e da participação esportiva em diferentes fases da infância e da adolescência. Recomenda que atividades, regras, instruções e níveis de competição sejam adequados à idade e ao estágio de desenvolvimento. Nas fases iniciais, prioriza brincadeira, segurança e habilidades fundamentais; com o avanço da idade, propõe progressão gradual para habilidades específicas, treinamento e competição, sem perder de vista diferenças individuais e mudanças relacionadas à puberdade.", keyPoint: "A participação esportiva deve evoluir de forma gradual, segura e compatível com cada fase do desenvolvimento.", limitation: "É um material educacional amplo, não um protocolo clínico nem uma prescrição individual de treinamento.", url: "https://worldathletics.org/download/download?filename=538bb448-c750-452d-b01a-144b10a51aa6.pdf&urlslug=Chapter+4%3A+Growth+and+Development" }
] as const;
