export const circuitFaq = [
  ["Quem pode participar?", "Atletas brasileiros das categorias Sub 10 a Sub 14, com autorização de um responsável legal, residentes no Brasil ou no exterior. Em 2026, isso corresponde aos nascidos de 2017 a 2013."],
  ["Preciso morar perto de uma pista?", "Não. São aceitas competições oficiais, pistas de 400 metros e percursos abertos."],
  ["A participação é gratuita?", "Sim, nesta primeira edição a participação é gratuita."],
  ["Posso participar mais de uma vez?", "Sim. Apenas a melhor marca aprovada será considerada em cada período."],
  ["Como minha categoria será definida?", "Pelo ano de nascimento e pela idade que o atleta completa em 2026: Sub 10 = nascidos em 2017 (9 anos); Sub 11 = 2016 (10 anos); Sub 12 = 2015 (11 anos); Sub 13 = 2014 (12 anos); e Sub 14 = 2013 (13 anos). A categoria não muda no decorrer da edição."],
  ["Posso correr acompanhado?", "Sim. É permitido correr em grupo ou com um pacer humano, sem auxílio físico ou motorizado."],
  ["Um treinador pode enviar a atividade?", "Sim, desde que exista autorização do pai, mãe ou responsável legal."],
  ["O vídeo precisa estar público?", "Sim. Ele deve permanecer público até a conclusão da análise."],
  ["O vídeo ou o Strava aparecerão no ranking?", "Não. Links e evidências ficam restritos à comissão."],
  ["Posso usar uma atividade de esteira ou manual?", "Não. Percursos abertos precisam ser registrados ao ar livre por dispositivo ou aplicativo compatível."],
  ["O percurso pode ser em descida?", "Não. O ponto final deve estar na mesma elevação ou acima do inicial, respeitada a tolerância técnica."],
  ["Uma atividade com mais de 1 km pode ser usada?", "Sim, quando for possível validar um trecho contínuo de pelo menos 1.000 metros."],
  ["Quanto tempo demora a análise?", "O status fica disponível no painel. Casos inconclusivos seguem para avaliação humana."],
  ["Uma marca oficial entra automaticamente?", "Somente quando todas as informações forem confirmadas. Caso contrário, seguirá para análise manual."],
  ["Como funcionam as premiações?", "Cada prêmio segue o período, as categorias e os critérios publicados no regulamento da edição."],
  ["Ganhar garante vaga no 11Run Futuro?", "Não. Atletas elegíveis ainda passam por avaliação presencial e homologação da comissão."],
  ["Por que enviar um documento?", "Para confirmar identidade e idade. O arquivo é privado e nunca aparece no ranking."],
  ["Posso corrigir uma inscrição?", "Sim. O responsável pode responder a uma solicitação de correção pelo painel de acompanhamento."],
  ["É obrigatório apresentar atestado médico?", "Não. O Desafio Virtual não exige atestado médico. Para participar, o pai, a mãe, o tutor ou o responsável legal deve confirmar o próprio CPF e aceitar o termo de saúde e responsabilidade antes do envio da atividade."],
  ["O que o responsável declara no termo?", "Declara que a criança está, na data do teste, em boas condições gerais de saúde e assume integral responsabilidade pela autorização, preparação, supervisão, hidratação, escolha do local e por ocorrências antes, durante e depois da atividade."],
  ["Quem deve acompanhar o teste?", "A criança deve ser acompanhada por um adulto responsável, em local seguro, com percurso adequado, hidratação disponível e condições compatíveis com a idade e o preparo do atleta."],
  ["Quando a atividade deve ser interrompida?", "Imediatamente diante de dor, falta de ar fora do esperado, tontura, desmaio, mal-estar, alteração incomum ou qualquer outro sinal de risco. Em caso de dúvida sobre a saúde da criança, o responsável deve buscar orientação profissional antes do teste."],
  ["A 11Run acompanha o teste presencialmente?", "Não. A participação é virtual e a 11Run não escolhe, fiscaliza ou controla presencialmente o local, a preparação ou a execução da atividade. Essas decisões e a supervisão são de responsabilidade do pai, mãe, tutor ou responsável legal."]
] as const;

export const circuitRegulations = [
  ["1. Do projeto", "O Circuito Virtual 11Run incentiva a corrida, acompanha a evolução e amplia oportunidades para crianças de todo o Brasil. A primeira edição chama-se Desafio Virtual 1km 11Run Futuro."],
  ["2. Do período", "A edição será realizada de 1º de agosto a 15 de dezembro de 2026. As inscrições já estão abertas; atividades com data anterior ao início serão registradas como realizadas em 1º de agosto de 2026. Fechamentos mensais, trimestrais e finais seguirão as datas publicadas."],
  ["3. Dos participantes e categorias", "Podem participar exclusivamente atletas brasileiros das categorias Sub 10 a Sub 14, residentes no Brasil ou no exterior. Para toda a edição de 2026, a classificação é fixa: Sub 10 — nascidos em 2017, que completam 9 anos em 2026; Sub 11 — nascidos em 2016, que completam 10 anos; Sub 12 — nascidos em 2015, que completam 11 anos; Sub 13 — nascidos em 2014, que completam 12 anos; Sub 14 — nascidos em 2013, que completam 13 anos. A categoria é definida pelo ano de nascimento e não muda na data do aniversário."],
  ["4. Da autorização", "A participação exige autorização expressa do responsável legal. Treinadores podem auxiliar o envio, mas não substituem esse consentimento."],
  ["5. Da distância", "Todos os resultados devem corresponder a 1.000 metros. Distâncias inferiores não serão aceitas."],
  ["6. Das formas de participação", "São aceitas marcas de competição oficial, teste em pista oficial de 400 metros e teste em percurso aberto, cada uma com comprovação própria."],
  ["7. Das competições oficiais", "É obrigatório informar competição, data, marca e resultado público. A marca só será oficial após confirmação."],
  ["8. Dos testes em pista", "O teste deve ocorrer em pista de 400 metros, completando duas voltas e 200 metros. O vídeo precisa permitir análise da largada, percurso e chegada."],
  ["9. Dos percursos abertos", "O percurso precisa ter ao menos 1.000 metros, registro eletrônico e vídeo público. O ponto final deve estar na mesma elevação ou acima do inicial, respeitada a tolerância."],
  ["10. Do acompanhamento", "É permitido correr acompanhado, em grupo ou com pacer humano. É proibido auxílio físico, revezamento, transporte parcial ou vantagem motorizada."],
  ["11. Das tentativas", "O atleta pode enviar quantas atividades desejar. Apenas a melhor marca aprovada em cada período participa da classificação."],
  ["12. Da validação", "A comissão pode solicitar novas informações, vídeo, acesso temporário, correção ou novo teste. Nenhuma rejeição automática é definitiva sem revisão humana."],
  ["13. Do ranking", "O ranking é separado pelas categorias Sub 10, Sub 11, Sub 12, Sub 13 e Sub 14 e por gênero esportivo. Apenas marcas aprovadas geram posição e direito a premiação."],
  ["14. Dos desempates", "Prevalecem menor tempo, maior nível de comprovação e marca realizada primeiro. A comissão pode solicitar teste em posições premiadas."],
  ["15. Das premiações", "Prêmios dependem da homologação, conferência documental e cumprimento do regulamento. Itens podem ser substituídos por equivalentes."],
  ["16. Do teste final", "Finalistas e candidatos ao 11Run Futuro podem ser convocados para teste presencial. Despesas só serão cobertas quando expressamente informado."],
  ["17. Do 11Run Futuro", "A liderança não garante ingresso. A decisão considera resultado, evolução, comprometimento, contexto familiar, disponibilidade e avaliação da comissão."],
  ["18. Da desclassificação", "Fraude, dados falsos, documentos falsos, atividade de terceiros, edição impeditiva do vídeo, distância inferior, descida indevida ou auxílio proibido podem causar desclassificação."],
  ["19. Dos dados pessoais", "Os dados são usados para identidade, idade, validação, contato, ranking e premiações. CPF, documentos, contatos e evidências não são públicos."],
  ["20. Da imagem e vídeo", "A análise privada da evidência, publicação no ranking e uso promocional são consentimentos separados. A autorização promocional é opcional."],
  ["21. Das decisões", "Casos não previstos serão analisados pela comissão. O regulamento pode ser atualizado para aumentar segurança e igualdade sem retirar direitos adquiridos."],
  ["22. Do termo de saúde e responsabilidade", "Não é exigido atestado médico para participar. O pai, a mãe, o tutor ou o responsável legal deve confirmar o próprio CPF e aceitar o termo declarando que a criança está, na data do teste, em boas condições gerais de saúde para realizar a atividade."],
  ["23. Da responsabilidade do responsável legal", "O responsável legal assume integral responsabilidade pela decisão de autorizar a participação e por todos os cuidados antes, durante e depois do teste, incluindo preparação, supervisão contínua, hidratação, vestuário, condições climáticas, escolha e segurança do percurso, deslocamentos e atendimento diante de qualquer intercorrência."],
  ["24. Da segurança e interrupção", "A atividade deve ocorrer sob acompanhamento de um adulto responsável e ser interrompida imediatamente diante de dor, falta de ar fora do esperado, tontura, desmaio, mal-estar, alteração incomum ou qualquer sinal de risco. Em caso de dúvida sobre a condição de saúde da criança, o responsável deve buscar orientação profissional antes da realização do teste."],
  ["25. Do caráter virtual", "A 11Run recebe e analisa as evidências enviadas, mas não escolhe, fiscaliza ou controla presencialmente o local, a preparação ou a execução da atividade. O aceite do termo registra a declaração e as responsabilidades do responsável legal, sem afastar direitos e deveres que não possam ser excluídos pela legislação aplicável."]
] as const;

export const mandatoryConsents = [
  ["LEGAL_GUARDIAN", "Declaro ser pai, mãe, tutor ou responsável legal pelo atleta."],
  ["BRAZILIAN_NATIONALITY", "Declaro que o atleta possui nacionalidade brasileira, residindo no Brasil ou no exterior."],
  ["DATA_TRUE", "Confirmo que os dados fornecidos são verdadeiros."],
  ["PARTICIPATION", "Autorizo a participação do atleta no Circuito Virtual 11Run."],
  ["DATA_PROCESSING", "Autorizo o tratamento dos dados necessários para inscrição, validação, ranking e premiação."],
  ["RANKING_PUBLICATION", "Autorizo a publicação do nome público, cidade, estado, categoria e marca no ranking."],
  ["REGULATIONS", "Li e aceito o regulamento."],
  ["ACTIVITY_AUTHENTICITY", "Declaro que a atividade foi realizada pelo atleta cadastrado."],
  ["PUBLIC_EVIDENCE", "Confirmo que os links permanecerão públicos durante a análise."],
  ["GUARDIAN_HEALTH_RESPONSIBILITY", "Declaro que a criança está em boas condições gerais de saúde e assumo integral responsabilidade pela autorização, preparação, supervisão e por ocorrências antes, durante e depois do teste."]
] as const;
