import type { Metadata } from "next";
import Link from "next/link";
import { ArrowDown, ArrowRight, FlaskConical } from "lucide-react";
import { NeurorespiratoryExperience } from "@/components/NeurorespiratoryExperience";
import { respiratoryFaq } from "@/lib/neurorespiratory-content";
import styles from "./page.module.css";

const title = "Respiração, cérebro e resistência no fundismo";
const description = "Entenda o que a ciência sabe sobre respiração lenta, HRV, treinamento muscular inspiratório, respiração nasal e modulação neurorespiratória em corredores e crianças.";
const path = "/referencias/analises/modulacao-neurorespiratoria-fundismo";

export const metadata: Metadata = { title, description, keywords: ["modulação neurorespiratória", "respiração para corredores", "respiração no fundismo", "treinamento muscular inspiratório", "HRV para atletas", "biofeedback respiratório", "respiração nasal na corrida", "educação respiratória", "percepção de esforço"], alternates:{canonical:path}, openGraph:{title,description,type:"article",url:path}, twitter:{card:"summary_large_image",title,description} };

export default function NeurorespiratoryAnalysisPage(){
  const origin=process.env.NEXT_PUBLIC_SITE_URL??"https://11run.com.br";
  const schemas=[{"@context":"https://schema.org","@type":"Article",headline:title,description,datePublished:"2026-08-06",dateModified:"2026-08-06",author:{"@type":"Person",name:"Seiti Katsumi"},publisher:{"@type":"Organization",name:"11RUN",url:origin},mainEntityOfPage:`${origin}${path}`},{"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Início",item:origin},{"@type":"ListItem",position:2,name:"Referências",item:`${origin}/referencias/ranking-brasil`},{"@type":"ListItem",position:3,name:"Análises",item:`${origin}/referencias/analises`},{"@type":"ListItem",position:4,name:"Respiração, cérebro e resistência",item:`${origin}${path}`}]},{"@context":"https://schema.org","@type":"FAQPage",mainEntity:respiratoryFaq.map(([question,answer])=>({"@type":"Question",name:question,acceptedAnswer:{"@type":"Answer",text:answer}}))}];
  return <article className={styles.page}>{schemas.map((schema,index)=><script key={index} type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,"\\u003c")}}/>)}<nav className={styles.breadcrumb} aria-label="Trilha de navegação"><Link href="/">Início</Link><span>/</span><Link href="/referencias/ranking-brasil">Referências</Link><span>/</span><strong>Análises</strong><span>/</span><b>Respiração, cérebro e resistência</b></nav><header className={styles.hero}><div className={styles.heroCopy}><span className={styles.eyebrow}>Análises 11RUN · Fisiologia e desenvolvimento</span><h1>Cada passada exige energia.<em>Cada respiração organiza a resposta.</em></h1><p>Respiração, cérebro, coração, músculos e percepção trabalham como um sistema integrado — sem transformar a respiração em promessa milagrosa.</p><div className={styles.actions}><a href="#conceito">Começar a análise <ArrowDown/></a><Link href="/onze-futuro">Conhecer o Onze Futuro <ArrowRight/></Link><a href="#ciencia">Ver as evidências <FlaskConical/></a></div><small>Fisiologia · Neurociência · Endurance · Infância protegida · Aplicação responsável</small></div><div className={styles.heroVisual} aria-label="Linhas de respiração, batimentos e passadas avançam de forma integrada"><div className={styles.air}/><div className={styles.pulse}/><div className={styles.steps}/><span>Respirar não é um atalho.<br/>É parte do sistema.</span></div></header><nav className={styles.jumpNav} aria-label="Nesta análise">{[["Conceito","conceito"],["O sistema","sistema"],["Práticas","praticas"],["Evidências","evidencias"],["HRV e força","hrv"],["Na corrida","corrida"],["Segurança","seguranca"],["Mitos","mitos"],["Programa 11RUN","programa"],["Ciência","ciencia"],["Dúvidas","duvidas"]].map(([label,id])=><a key={id} href={`#${id}`}>{label}</a>)}</nav><NeurorespiratoryExperience/><section className={styles.signature}><div><span className={styles.eyebrow}>Análises 11RUN</span><h2>Educar a percepção antes de tentar controlar a resposta.</h2><p>A ciência respiratória pode ampliar linguagem corporal e segurança quando suas limitações permanecem visíveis e a criança continua no centro das decisões.</p></div><div><strong>Seiti Katsumi</strong><span>Fundador da 11RUN</span></div></section></article>;
}
