import assert from "node:assert/strict";
import test from "node:test";
import { analyzeOlympicPathway, potentialBandFor, validatePathwayInput, type ComparableSource, type PathwayInput } from "../src/lib/olympic-pathway/core.ts";

const input:PathwayInput={event:1500,performance:"4:32.8",ageYears:13,ageMonths:4,gender:"F",representedCountry:"BR",performanceDate:"2026-07-12",context:"official",surface:"outdoor"};
const source:ComparableSource={key:"NO",label:"Noruega",country:"NO",category:"13 anos",alignment:"exact_age",sourceUrl:"https://example.com",status:"available",performancesMs:Array.from({length:100},(_,index)=>250000+index*3000)};
const markMs=272800;
function ranked(key:string,position:number,alignment:ComparableSource["alignment"]="exact_age"):ComparableSource{return{...source,key,label:key,alignment,performancesMs:Array.from({length:100},(_,index)=>index<position-1?markMs-(position-index)*1000:markMs+(index-position+1)*1000)}}

test("valida tempo, idade, categoria e data",()=>{assert.equal(validatePathwayInput(input).valid,true);assert.equal(validatePathwayInput({...input,performance:"3:75"}).valid,false);assert.equal(validatePathwayInput({...input,ageYears:8}).valid,false);});
test("calcula posição e aplica coeficiente recreativo de desenvolvimento",()=>{const result=analyzeOlympicPathway(input,[source],"2026-08-15T12:00:00.000Z");assert.equal(result.comparisons[0].position,9);assert.equal(result.potentialScore,95);assert.equal(result.probabilityCalibrated,false);assert.equal(result.confidence,"projeção recreativa");assert.equal(result.developmentBonus,3);});
test("projeta base recreativa infantil mesmo sem ranking disponível",()=>{const unavailable={...source,status:"unavailable" as const,performancesMs:[]};const result=analyzeOlympicPathway(input,[unavailable]);assert.equal(result.potentialScore,5);assert.equal(result.projectionBasis,"developmental-baseline");assert.equal(result.comparableSources,0);});
test("não inventa posição além da lista disponível",()=>{const result=analyzeOlympicPathway({...input,performance:"20:00"},[source]);assert.equal(result.comparisons[0].position,null);assert.equal(result.comparisons[0].beyondAvailableList,true);});
test("3.000 m abre rotas de 1.500 m e 5.000 m",()=>{const result=analyzeOlympicPathway({...input,event:3000,performance:"10:00"},[source]);assert.deepEqual(result.threeKRoutes.map(route=>route.distance),[1500,5000]);assert.ok(result.threeKRoutes.every(route=>Number.isFinite(route.divergencePercent)));});
test("aplica o peso de alinhamento uma única vez antes do bônus infantil",()=>{const result=analyzeOlympicPathway(input,[ranked("BR",1),ranked("WORLD",100,"projected_event")]);assert.equal(result.potentialScore,70);});
test("Top 30 de EUA garante destaque internacional e piso 35",()=>{const result=analyzeOlympicPathway(input,[ranked("US",30,"projected_event"),ranked("BR",100),ranked("WORLD",100),ranked("KE",100)]);assert.equal(result.potentialScore,35);assert.equal(result.potentialBand,"international");assert.ok(result.badges.some(badge=>badge.key==="international-top-30"));});
test("Top 10 do Japão garante piso 55",()=>{const result=analyzeOlympicPathway(input,[ranked("JP",10,"projected_event"),ranked("BR",100),ranked("WORLD",100),ranked("KE",100)]);assert.equal(result.potentialScore,55);assert.ok(result.badges.some(badge=>badge.key==="international-top-10"));});
test("Top 3 da Noruega garante piso 75",()=>{const result=analyzeOlympicPathway(input,[ranked("NO",3,"projected_event"),ranked("BR",100),ranked("WORLD",100),ranked("KE",100)]);assert.equal(result.potentialScore,75);assert.ok(result.badges.some(badge=>badge.key==="international-top-3"));});
test("base indisponível não libera conquista",()=>{const result=analyzeOlympicPathway(input,[{...ranked("US",3),status:"unavailable"}]);assert.equal(result.potentialScore,5);assert.equal(result.badges.some(badge=>badge.key.startsWith("international")),false);});
test("Top 50 nacional mantém o sonho recreativo ativo",()=>{const result=analyzeOlympicPathway(input,[ranked("BR",50)]);assert.ok(result.nationalTop50.some(item=>item.key==="BR"));assert.ok(result.badges.some(badge=>badge.key==="national-top-50"));});
test("mantém placar mínimo de um para adulto e classifica narrativas",()=>{const result=analyzeOlympicPathway({...input,ageYears:20},[ranked("BR",100)]);assert.equal(result.potentialScore,1);assert.deepEqual([1,15,35,55,75].map(score=>potentialBandFor(score)),["starting","moving","international","promising","extraordinary"]);});
test("5.000 m aos 9 anos recebe piso avançado mesmo sem referências",()=>{const result=analyzeOlympicPathway({...input,event:5000,performance:"24:00",ageYears:9,ageMonths:0},[{...source,status:"unavailable",performancesMs:[]}]);assert.equal(result.potentialScore,35);assert.equal(result.youngEndurance.active,true);assert.equal(result.youngEndurance.floor,35);assert.ok(result.badges.some(badge=>badge.key==="young-endurance"));});
test("3.000 m até 12 anos recebe coeficiente próprio",()=>{const result=analyzeOlympicPathway({...input,event:3000,performance:"14:00",ageYears:12,ageMonths:0},[{...source,status:"unavailable",performancesMs:[]}]);assert.equal(result.potentialScore,22);assert.equal(result.youngEndurance.bonus,3);});
test("800 e 1.500 m não recebem bônus de distância longa",()=>{const result=analyzeOlympicPathway({...input,event:1500,ageYears:9,ageMonths:0},[{...source,status:"unavailable",performancesMs:[]}]);assert.equal(result.youngEndurance.active,false);assert.equal(result.potentialScore,5);});
test("1.000 m é aceito e combina referências projetadas de 800 e 1.500 m",()=>{const result=analyzeOlympicPathway({...input,event:1000,performance:"3:05",ageYears:11,ageMonths:0},[{...source,key:"US-800",country:"US",alignment:"projected_event",performancesMs:Array.from({length:40},(_,index)=>170000+index*1000)},{...source,key:"US-1500",country:"US",alignment:"projected_event",performancesMs:Array.from({length:40},(_,index)=>172000+index*1000)}]);assert.equal(result.comparableSources,2);assert.ok(result.potentialScore!==null&&result.potentialScore>=1);});
test("atleta adulto recebe a régua das 50 melhores marcas mundiais",()=>{const result=analyzeOlympicPathway({...input,event:1500,ageYears:24,ageMonths:0},[{...source,key:"WORLD",country:"WORLD",category:"SENIOR",alignment:"senior",performancesMs:Array.from({length:80},(_,index)=>210000+index*500)}]);assert.equal(result.worldTop50.length,50);assert.deepEqual(result.worldTop50[0],{position:1,performanceMs:210000});});
