"use client";

import { CheckCircle2, ClipboardCheck, FileDown, Medal, RefreshCw, ShieldAlert, Users, XCircle, type LucideIcon } from "lucide-react";
import { useState } from "react";
import styles from "./CircuitAdmin.module.css";

type Metrics={athletes:number;guardians:number;submissions:number;receivedToday:number;underReview:number;approved:number;rejected:number;projectedShirts:number};
type Evidence={id:string;evidence_type:string;original_url:string|null;private_file_id:string|null;accessibility_status:string};
type Submission={id:string;athlete_name:string;public_name:string;category_age:number;gender:string;formattedTime:string;submission_type:string;status:string;activity_date:string;city:string;state:string;guardian_name:string;guardian_email:string;guardian_phone:string;document_file_id:string;evidence?:Evidence[]} & Record<string,unknown>;
const labels:Record<string,string>={UNDER_REVIEW:"Em análise",APPROVED:"Aprovada",REJECTED:"Rejeitada",CORRECTION_REQUESTED:"Correção solicitada",DISQUALIFIED:"Desclassificada"};

export function CircuitAdmin({initialMetrics,initialSubmissions}:{initialMetrics:Metrics;initialSubmissions:Submission[]}){
  const [metrics,setMetrics]=useState(initialMetrics);const [items,setItems]=useState(initialSubmissions);const [active,setActive]=useState<Submission|null>(null);const [reason,setReason]=useState("");const [verifiedTime,setVerifiedTime]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  async function refresh(){const r=await fetch("/api/admin/circuito-virtual");const j=await r.json();setMetrics(j.metrics);setItems(j.submissions)}
  async function openSubmission(id:string){setError("");const r=await fetch(`/api/admin/circuito-virtual/submissions/${id}`);const j=await r.json();if(!r.ok)return setError(j.error||"Falha ao carregar.");setActive(j.submission)}
  async function decide(status:string){if(!active||!reason.trim())return setError("Informe uma justificativa para registrar a decisão.");setBusy(true);setError("");const r=await fetch(`/api/admin/circuito-virtual/submissions/${active.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status,reason,verifiedTime:verifiedTime||undefined})});const j=await r.json();setBusy(false);if(!r.ok)return setError(j.error||"Falha ao atualizar.");setActive(null);setReason("");setVerifiedTime("");await refresh()}
  return <main className={`admin-panel ${styles.panel}`}>
    <section className={styles.hero}><div><span>Circuito Virtual</span><h1>Inscrições, validação e ranking.</h1><p>Aprovação manual segura enquanto integrações externas não estiverem disponíveis.</p></div><button onClick={refresh}><RefreshCw size={16}/>Atualizar</button></section>
    <section className={styles.metrics}>{([[Users,"Atletas",metrics.athletes],[ClipboardCheck,"Atividades",metrics.submissions],[ShieldAlert,"Em análise",metrics.underReview],[CheckCircle2,"Aprovadas",metrics.approved],[XCircle,"Rejeitadas",metrics.rejected],[Medal,"Camisetas projetadas",metrics.projectedShirts]] as Array<[LucideIcon,string,number]>).map(([Icon,label,value])=><article key={label}><Icon size={19}/><span>{label}</span><strong>{value}</strong></article>)}</section>
    <section className={styles.queue}><div className={styles.sectionTitle}><div><span>Fila técnica</span><h2>Atividades recebidas</h2></div><button type="button" onClick={()=>window.open("/api/admin/circuito-virtual/export","_blank")}><FileDown size={16}/>Exportar CSV</button></div>
      <div className={styles.table}><div className={styles.head}><span>Atleta</span><span>Categoria</span><span>Marca</span><span>Modalidade</span><span>Status</span><span></span></div>{items.map(item=><button className={styles.row} key={item.id} onClick={()=>openSubmission(item.id)}><strong>{item.athlete_name}</strong><span>{item.category_age} anos · {item.gender==="FEMALE"?"F":"M"}</span><b>{item.formattedTime}</b><span>{item.submission_type.replaceAll("_"," ")}</span><em>{labels[item.status]||item.status}</em><span>Revisar →</span></button>)}{!items.length&&<p className={styles.empty}>Nenhuma atividade recebida ainda.</p>}</div>
    </section>
    {active&&<div className={styles.overlay} role="dialog" aria-modal="true"><div className={styles.drawer}><button className={styles.close} onClick={()=>setActive(null)}>×</button><span className={styles.kicker}>Revisão técnica</span><h2>{active.athlete_name}</h2><div className={styles.details}><p><small>Nome público</small><strong>{active.public_name}</strong></p><p><small>Categoria</small><strong>{active.category_age} anos · {active.gender==="FEMALE"?"Feminino":"Masculino"}</strong></p><p><small>Marca declarada</small><strong>{active.formattedTime}</strong></p><p><small>Atividade</small><strong>{active.activity_date} · {active.city}/{active.state}</strong></p><p><small>Responsável</small><strong>{active.guardian_name}</strong><span>{active.guardian_email} · {active.guardian_phone}</span></p><p><small>Status</small><strong>{labels[active.status]||active.status}</strong></p></div><div className={styles.evidence}><strong>Evidências privadas</strong><div><span>Documento de identidade e idade</span><a href={`/api/admin/circuito-virtual/files/${active.document_file_id}`} target="_blank" rel="noreferrer">Baixar documento</a></div>{active.evidence?.map(item=><div key={item.id}><span>{item.evidence_type.replaceAll("_"," ")}</span>{item.original_url?<a href={item.original_url} target="_blank" rel="noreferrer">Abrir link seguro ↗</a>:null}{item.private_file_id?<a href={`/api/admin/circuito-virtual/files/${item.private_file_id}`} target="_blank" rel="noreferrer">Baixar documento</a>:null}</div>)}</div><label>Marca verificada (opcional)<input placeholder="03:42.18" value={verifiedTime} onChange={e=>setVerifiedTime(e.target.value)}/></label><label>Justificativa obrigatória<textarea rows={4} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Registre as evidências e o motivo da decisão."/></label>{error&&<p className={styles.error}>{error}</p>}<div className={styles.actions}><button disabled={busy} onClick={()=>decide("APPROVED")}><CheckCircle2/>Aprovar</button><button disabled={busy} onClick={()=>decide("CORRECTION_REQUESTED")}><ShieldAlert/>Pedir correção</button><button disabled={busy} onClick={()=>decide("REJECTED")}><XCircle/>Rejeitar</button></div></div></div>}
  </main>
}
