"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowRight, Check, Clipboard, Download, Gauge, History, Printer, Save, Share2, ShieldCheck, Sparkles, Timer, Trash2 } from "lucide-react";
import { TEST_DISTANCES } from "@/config/running-formulas";
import { calculateFormulaResult, formatDuration, parseDuration } from "@/lib/running-formulas";
import styles from "@/app/referencias/calculadoras/formulas/formulas.module.css";

type Saved = { id:string; distanceM:number; durationSec:number; vdot:number; k:number; createdAt:string };
const HISTORY_KEY = "11run.formulas.history.v1";

function pace(seconds:number){return `${formatDuration(seconds)}/km`;}
function paceUrl(distance:number, seconds:number){return `/referencias/calculadoras/pace?distancia=${distance}&tempo=${encodeURIComponent(formatDuration(seconds))}`;}

export function FormulaCalculator(){
  const [distance,setDistance]=useState(3000); const [duration,setDuration]=useState("10:00"); const [context,setContext]=useState("official");
  const [surface,setSurface]=useState("track"); const [audience,setAudience]=useState("none"); const [k,setK]=useState(1.06);
  const [submitted,setSubmitted]=useState(true); const [error,setError]=useState(""); const [copied,setCopied]=useState(false); const [history,setHistory]=useState<Saved[]>([]);
  const resultTitle=useRef<HTMLHeadingElement>(null);
  const seconds=parseDuration(duration); const rawPace=seconds ? seconds/(distance/1000) : 0;
  const result=useMemo(()=>seconds&&rawPace>=100&&rawPace<=900?calculateFormulaResult({distanceM:distance,durationSec:seconds,riegelExponent:k,context,surface,audience}):null,[audience,context,distance,k,rawPace,seconds,surface]);
  useEffect(()=>{try{const parsed=JSON.parse(localStorage.getItem(HISTORY_KEY)||"[]");setHistory(Array.isArray(parsed)?parsed.slice(0,20):[]);}catch{setHistory([]);}},[]);
  useEffect(()=>{const q=new URLSearchParams(window.location.search);const d=Number(q.get("distancia"));const t=q.get("tempo");if(TEST_DISTANCES.includes(d as typeof TEST_DISTANCES[number])&&t&&parseDuration(t)){setDistance(d);setDuration(t);}},[]);
  function calculate(){if(!seconds){setError("Informe o tempo no formato mm:ss ou hh:mm:ss.");setSubmitted(false);return;}if(rawPace<100||rawPace>900){setError("Confira a distância e o tempo informados. O ritmo resultante está fora da faixa operacional desta calculadora.");setSubmitted(false);return;}setError("");setSubmitted(true);setTimeout(()=>resultTitle.current?.focus(),0);}
  function resultText(){if(!result)return "";return `Fórmulas 11RUN — ${distance} m em ${formatDuration(result.input.durationSec)}\nRitmo: ${pace(result.paceSecKm)} · Velocidade: ${result.speedKmh.toFixed(2)} km/h · VDOT estimado: ${result.vdot.toFixed(1)}\nEstimativa matemática: https://11run.com.br/referencias/calculadoras/formulas`;}
  async function copy(){await navigator.clipboard.writeText(resultText());setCopied(true);setTimeout(()=>setCopied(false),1800);}
  async function share(){const url=new URL(window.location.href);url.search=`?distancia=${distance}&tempo=${encodeURIComponent(duration)}&metodo=vdot`;if(navigator.share)await navigator.share({title:"Fórmulas 11RUN",text:resultText(),url:url.toString()});else{await navigator.clipboard.writeText(url.toString());setCopied(true);}}
  function save(){if(!result)return;const next=[{id:crypto.randomUUID(),distanceM:distance,durationSec:result.input.durationSec,vdot:result.vdot,k,createdAt:new Date().toISOString()},...history].slice(0,20);localStorage.setItem(HISTORY_KEY,JSON.stringify(next));setHistory(next);}
  function exportCard(){if(!result)return;const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1350"><rect width="100%" height="100%" fill="#f7f7f5"/><text x="90" y="120" font-family="Arial" font-size="42" font-weight="700">11RUN · FÓRMULAS</text><text x="90" y="310" font-family="Arial" font-size="116">${distance.toLocaleString("pt-BR")} m</text><text x="90" y="450" font-family="Arial" font-size="104" fill="#c94f00">${formatDuration(result.input.durationSec)}</text><text x="90" y="590" font-family="Arial" font-size="48">${pace(result.paceSecKm)} · ${result.speedKmh.toFixed(2)} km/h</text><text x="90" y="730" font-family="Arial" font-size="78">VDOT estimado ${result.vdot.toFixed(1)}</text><line x1="90" y1="820" x2="990" y2="820" stroke="#292929"/><text x="90" y="910" font-family="Arial" font-size="38">Estimativa matemática</text><text x="90" y="1200" font-family="Arial" font-size="34">11run.com.br/referencias/calculadoras/formulas</text></svg>`;const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([svg],{type:"image/svg+xml"}));a.download="11run-formulas.svg";a.click();URL.revokeObjectURL(a.href);}
  return <>
    <section className={styles.journey} id="calcular"><div className={styles.steps}><span><i><Check/></i>Escolha seu teste</span><span><i><Check/></i>Informe sua marca</span><span className={submitted&&result?styles.current:""}><i>3</i>Descubra seu mapa</span></div>
      <div className={styles.workspace}><div className={styles.form}>
        <span className={styles.eyebrow}>Resultado de referência</span><h2>Qual marca vamos interpretar?</h2>
        <fieldset><legend>Distância do teste</legend><div className={styles.distanceButtons}>{TEST_DISTANCES.map(d=><button type="button" className={distance===d?styles.active:""} onClick={()=>setDistance(d)} key={d}>{d.toLocaleString("pt-BR")} m</button>)}</div></fieldset>
        <label><span>Tempo do teste</span><input value={duration} onChange={e=>setDuration(e.target.value)} inputMode="decimal" placeholder="10:00" aria-invalid={Boolean(error)} aria-describedby="duration-help"/><small id="duration-help">Use mm:ss, hh:mm:ss ou décimos: 10:00.5</small></label>
        <div className={styles.selects}><label><span>Tipo do resultado</span><select value={context} onChange={e=>setContext(e.target.value)}><option value="official">Competição oficial</option><option value="track-test">Teste máximo em pista</option><option value="measured">Percurso aferido</option><option value="controlled">Treino controlado</option><option value="estimate">Estimativa pessoal</option></select></label><label><span>Superfície</span><select value={surface} onChange={e=>setSurface(e.target.value)}><option value="track">Pista</option><option value="road">Rua plana</option><option value="varied">Percurso com variação</option><option value="treadmill">Esteira</option><option value="none">Não informar</option></select></label><label><span>Público</span><select value={audience} onChange={e=>setAudience(e.target.value)}><option value="none">Não informar</option><option value="child">Criança de 9 a 13 anos</option><option value="teen">Adolescente de 14 a 17 anos</option><option value="adult">Adulto</option><option value="master">Master</option></select></label></div>
        <details><summary>Ajustar coeficiente de resistência</summary><div className={styles.advanced}><input type="range" min="1.03" max="1.12" step="0.01" value={k} onChange={e=>setK(Number(e.target.value))}/><input type="number" min="1.03" max="1.12" step="0.01" value={k} onChange={e=>setK(Number(e.target.value))}/><button type="button" onClick={()=>setK(1.06)}>Restaurar 1,06</button><p>Valores menores projetam menor queda de velocidade. Ajuste apenas quando houver histórico suficiente.</p></div></details>
        {error?<p className={styles.error} role="alert">{error}</p>:null}<div className={styles.formActions}><button type="button" onClick={calculate}>Calcular meu mapa <Sparkles/></button><button type="button" onClick={()=>{setDistance(3000);setDuration("10:00");setK(1.06);setError("");}}>Usar exemplo</button></div>
      </div>
      <aside className={styles.live}><span>Leitura instantânea</span><strong>{distance.toLocaleString("pt-BR")} m</strong><b>{seconds?formatDuration(seconds,true):"—"}</b><div><span>Ritmo médio<strong>{result?pace(result.paceSecKm):"—"}</strong></span><span>Velocidade<strong>{result?`${result.speedKmh.toFixed(2)} km/h`:"—"}</strong></span></div><small>Contexto e superfície qualificam a interpretação, sem alterar artificialmente a fórmula.</small></aside></div>
    </section>
    {submitted&&result?<section className={styles.results} aria-live="polite"><header><div><span className={styles.eyebrow}>Mapa calculado · referência matemática</span><h2 tabIndex={-1} ref={resultTitle}>Uma marca, várias leituras.</h2></div><div className={styles.actions}><button onClick={copy}>{copied?<Check/>:<Clipboard/>}{copied?"Copiado":"Copiar"}</button><button onClick={share}><Share2/>Compartilhar</button><button onClick={save}><Save/>Salvar</button><button onClick={exportCard}><Download/>Gerar card</button><button onClick={()=>window.print()}><Printer/>Imprimir</button></div></header>
      <div className={styles.summary}><article><Timer/><span>Resultado informado</span><strong>{formatDuration(result.input.durationSec,true)}</strong><small>{distance.toLocaleString("pt-BR")} m</small></article><article><Gauge/><span>Ritmo médio</span><strong>{pace(result.paceSecKm)}</strong><small>{result.speedKmh.toFixed(2)} km/h</small></article><article><Sparkles/><span>VDOT estimado</span><strong>{result.vdot.toFixed(1)}</strong><small>Índice, não VO₂máx medido</small></article><article><Gauge/><span>Velocidade aeróbia estimada</span><strong>{result.vdotSpeedKmh.toFixed(2)}</strong><small>km/h · {pace(result.vdotPaceSecKm)}</small></article></div>
      <section className={styles.projections}><div><span className={styles.eyebrow}>Riegel × Daniels–Gilbert</span><h3>Projeções equivalentes.</h3><p>Quanto mais distante do teste original, maior deve ser a cautela.</p></div><div className={styles.projectionGrid}>{result.projections.map(p=><article key={p.distanceM}><header><strong>{p.distanceM.toLocaleString("pt-BR")} m</strong>{p.isSource?<span>Marca de referência</span>:<span>{p.confidence==="good"?"Boa proximidade":p.confidence==="moderate"?"Cautela moderada":"Exploratória"}</span>}</header><dl><div><dt>Riegel</dt><dd>{formatDuration(p.riegelSeconds,true)}</dd></div><div><dt>VDOT</dt><dd>{formatDuration(p.vdotSeconds,true)}</dd></div><div><dt>Diferença</dt><dd>{p.differencePercent.toFixed(1)}%</dd></div></dl><a href={paceUrl(p.distanceM,p.vdotSeconds)}>Ver passagens desta marca <ArrowRight/></a></article>)}</div></section>
      <section className={styles.zones}><header><span className={styles.eyebrow}>Zonas 11RUN · interpretação operacional baseada no VDOT</span><h3>Seis referências, com nome e objetivo.</h3><p>Relógios, plataformas e treinadores podem usar divisões diferentes. Compare o objetivo, não apenas o número.</p></header><div className={styles.zoneGrid}>{result.zones.map(z=><details key={z.id} open={z.id==="Z2"||z.id==="Z4"}><summary><span>{z.id}</span><div><strong>{z.name}</strong><small>{pace(z.fastPace)} a {pace(z.slowPace)}</small></div><b>{z.rpe}</b></summary><div className={styles.zoneBody}><p>{z.purpose}</p><dl><div><dt>Velocidade</dt><dd>{z.minSpeedKmh.toFixed(2)}–{z.maxSpeedKmh.toFixed(2)} km/h</dd></div><div><dt>Teste da fala</dt><dd>{z.talk}</dd></div><div><dt>Exemplos</dt><dd>{z.examples.join(" · ")}</dd></div></dl><div className={styles.segments}>{z.segments.map(s=><span key={s.meters}>{s.meters} m<strong>{formatDuration(s.fast,true)}–{formatDuration(s.slow,true)}</strong></span>)}</div>{audience==="child"?<small className={styles.childNotice}>Para crianças, priorize variedade, técnica, supervisão e prazer. Estes tempos são informativos, não uma prescrição de volume.</small>:null}</div></details>)}</div></section>
      <section className={styles.notice}><ShieldCheck/><div><span>Referência, não sentença</span><h3>A fórmula amplia a leitura da marca.</h3><p>Uma marca não mede sozinha o potencial. As projeções não consideram integralmente maturação, experiência, economia, reserva anaeróbia, sono, saúde, clima ou estratégia. A ferramenta não seleciona, exclui, diagnostica, prevê carreira nem substitui avaliação médica, fisiológica ou orientação profissional.</p></div></section>
      <section className={styles.history}><header><History/><div><span>Histórico neste dispositivo</span><strong>{history.length} resultado{history.length===1?"":"s"} salvo{history.length===1?"":"s"}</strong></div>{history.length?<button onClick={()=>{localStorage.removeItem(HISTORY_KEY);setHistory([]);}}><Trash2/>Limpar</button>:null}</header>{history.length?<div>{history.slice(0,6).map(h=><article key={h.id}><strong>{h.distanceM.toLocaleString("pt-BR")} m · {formatDuration(h.durationSec)}</strong><span>VDOT {h.vdot.toFixed(1)} · k {h.k.toFixed(2)}</span><small>{new Date(h.createdAt).toLocaleString("pt-BR")}</small></article>)}</div>:<p>Use “Salvar” para guardar explicitamente até 20 cálculos neste navegador.</p>}</section>
    </section>:null}
  </>;
}
