"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowRight, Check, ChevronDown, ExternalLink, Globe2, Languages, Network, School, ShieldCheck, X } from "lucide-react";
import { countries, ecosystemNodes, evidenceClaims, lateStartFaq, lateStartReferences, startingLines } from "@/lib/late-start-content";
import styles from "@/app/referencias/analises/o-fundo-comeca-na-infancia/page.module.css";

const track=(event:string)=>window.dispatchEvent(new CustomEvent("11run:analytics",{detail:{event}}));

export function LateStartExperience(){
  const [progress,setProgress]=useState(0),[country,setCountry]=useState(0),[filter,setFilter]=useState("Todos"),[nodes,setNodes]=useState<string[]>([]);
  const axes=useMemo(()=>["Todos",...Array.from(new Set(lateStartReferences.map(item=>item.axis)))],[]);
  const references=filter==="Todos"?lateStartReferences:lateStartReferences.filter(item=>item.axis===filter);
  useEffect(()=>{track("late_start_analysis_view");const fired=new Set<number>();const onScroll=()=>{const root=document.documentElement;const value=Math.min(100,Math.round(root.scrollTop/Math.max(1,root.scrollHeight-root.clientHeight)*100));setProgress(value);[25,50,75,90].forEach(point=>{if(value>=point&&!fired.has(point)){fired.add(point);track(`late_start_reading_${point}`)}})};onScroll();addEventListener("scroll",onScroll,{passive:true});return()=>removeEventListener("scroll",onScroll)},[]);
  const current=countries[country];
  return <>
    <div className={styles.readingProgress} aria-hidden="true"><span style={{width:`${progress}%`}}/></div>
    <section className={styles.verdict} id="pergunta"><span className={styles.eyebrow}>Parecer científico</span><h2>O Brasil não precisa especializar crianças mais cedo.</h2><p>Precisa oferecer movimento, repertório, contato com o atletismo, continuidade, ambientes seguros e caminhos visíveis antes que a adolescência chegue.</p><blockquote>Começar cedo no movimento não é o mesmo que começar cedo no volume.</blockquote></section>

    <section className={styles.section} id="ciencia"><header className={styles.heading}><span className={styles.eyebrow}>O paradoxo do sucesso precoce</span><h2>Resultado juvenil ajuda a contar uma história. Não prevê o final.</h2><p>Jovens de alto desempenho frequentemente começam a modalidade principal antes. Mas atletas adultos de nível mundial tendem a acumular mais experiências multiesportivas, entrada posterior e progressão inicial gradual.</p></header><div className={styles.transition}><div><strong>100%</strong><span>melhores Sub-18 observados</span></div><i/><div><strong>19–21%</strong><span>também alcançaram a elite adulta</span></div></div><small className={styles.note}>Dado de uma análise de 4.678 corredores internacionais de meio-fundo e fundo. Associação estatística não determina o destino de uma pessoa.</small></section>

    <section className={styles.section} id="comecos"><header className={styles.heading}><span className={styles.eyebrow}>Três linhas de partida</span><h2>Movimento, atletismo e especialização são processos diferentes.</h2></header><div className={styles.startGrid}>{startingLines.map((item,index)=><article key={item.title}><span>0{index+1} · {item.status}</span><h3>{item.title}</h3><p>{item.text}</p>{index<2?<Check/>:<X/>}</article>)}</div><div className={styles.accessCompare}><div><strong>Acesso precoce</strong><p>Variedade · prazer · aprendizagem · pertencimento · portas abertas</p></div><div><strong>Especialização precoce</strong><p>Predomínio de uma modalidade · volume · seleção · redução de escolhas</p></div></div></section>

    <section className={styles.section} id="mundo"><header className={styles.heading}><span className={styles.eyebrow}>Atlas de mecanismos</span><h2>Sete contextos. Nenhuma fórmula universal.</h2><p>Os países não são versões melhores ou piores do mesmo sistema. Cada contexto combina escola, comunidade, cultura, competição e transições de maneira própria.</p></header><div className={styles.countryTabs} role="tablist" aria-label="Países analisados">{countries.map((item,index)=><button key={item.id} role="tab" aria-selected={country===index} onClick={()=>{setCountry(index);track("late_start_country_open")}}>{item.country}</button>)}</div><article className={styles.countryPanel} role="tabpanel"><header><Globe2/><div><span>{current.level} evidência</span><h3>{current.country}</h3><p>{current.mechanism}</p></div></header><div className={styles.countryFacts}><div><strong>Papel da escola</strong><p>{current.school}</p></div><div><strong>Caminho visível</strong><p>{current.pathway}</p></div><div><strong>O Brasil pode adaptar</strong><p>{current.opportunity}</p></div><div><strong>Limitação</strong><p>{current.limitation}</p></div></div><footer><X/><p><strong>Não copiar:</strong> {current.avoid}</p></footer></article></section>

    <section className={styles.brazil} id="brasil"><div><span className={styles.eyebrow}>Brasil</span><h2>As peças existem. O caminho entre elas é que se rompe.</h2><p>Educação Física obrigatória, federações, categorias, clubes, projetos e competições são pontos reais. O problema é a desigualdade de acesso e a ausência de uma passagem contínua entre eles.</p></div><div className={styles.brokenPath} role="img" aria-label="Escola, projeto, clube e competição aparecem como pontos existentes, mas com conexões interrompidas"><span>Escola</span><i/><span>Projeto</span><i/><span>Clube</span><i/><span>Competição</span></div></section>

    <section className={styles.section} id="escola"><header className={styles.heading}><span className={styles.eyebrow}>A primeira porta</span><h2>A escola deve revelar possibilidades — não sentenciar talento.</h2></header><div className={styles.schoolGrid}><article><School/><h3>Experimentar</h3><p>Correr, saltar, lançar, cooperar e competir em formatos adequados.</p></article><article><Network/><h3>Conectar</h3><p>Orientar famílias e criar pontes com projetos, clubes e profissionais.</p></article><article><ShieldCheck/><h3>Proteger</h3><p>Interpretar desempenho com crescimento, maturação, contexto e direitos.</p></article></div></section>

    <section className={styles.section} id="ecossistema"><header className={styles.heading}><span className={styles.eyebrow}>Construtor de ecossistema</span><h2>Um caminho forte depende de conexões, não de um teste isolado.</h2><p>Ative os nós para visualizar a rede. A interação é educativa e não coleta nenhuma informação pessoal.</p></header><div className={styles.builder}>{ecosystemNodes.map(node=><button key={node} aria-pressed={nodes.includes(node)} onClick={()=>{setNodes(old=>old.includes(node)?old.filter(item=>item!==node):[...old,node]);track("late_start_brazil_ecosystem_interaction")}}>{nodes.includes(node)?<Check/>:<span/>}{node}</button>)}</div><div className={styles.builderStatus}><strong>{nodes.length}/10 conexões consideradas</strong><p>{nodes.length<4?"O talento ainda depende do acaso.":nodes.length<8?"O caminho começa a ganhar continuidade.":"Uma rede ampla protege transições e mantém diferentes futuros abertos."}</p></div></section>

    <section className={styles.onze} id="onze-futuro"><div><span className={styles.eyebrow}>Onze Futuro</span><h2>Começar pequeno para acompanhar com profundidade.</h2><p>A primeira turma de seis atletas é uma avaliação de viabilidade e acompanhamento de casos. Não comprova um modelo, não prevê carreira e não produz score de talento.</p></div><ul><li><Check/>Dados com contexto, não sentença</li><li><Check/>Formação esportiva e educacional</li><li><Check/>Proteção e supervisão humana</li><li><X/>Sem promessa de alto rendimento</li></ul></section>

    <section className={styles.section} id="evidencias"><header className={styles.heading}><span className={styles.eyebrow}>Níveis de evidência</span><h2>O que sabemos — e até onde podemos afirmar.</h2></header><div className={styles.evidenceGrid}>{evidenceClaims.map(item=><article key={item.claim}><span data-level={item.level}>{item.level}</span><h3>{item.claim}</h3><p>{item.interpretation}</p></article>)}</div><aside className={styles.limitations}><strong>O que esta comparação não consegue provar</strong><p>Definições e dados diferem entre países; atividade física não é treino; atletas de elite não representam populações; memória retrospectiva introduz viés; associação não prova causa; e sucesso olímpico não mede saúde ou inclusão.</p></aside></section>

    <section className={styles.section} id="fontes"><header className={styles.heading}><span className={styles.eyebrow}>Biblioteca científica e institucional</span><h2>Fontes próprias para cada mecanismo e país.</h2><p>Referências revisadas em 6 de agosto de 2026. Cada card explicita também sua principal limitação.</p></header><div className={styles.filters}>{axes.map(axis=><button key={axis} aria-pressed={filter===axis} onClick={()=>{setFilter(axis);track("late_start_mechanism_filter")}}>{axis}</button>)}</div><div className={styles.references}>{references.map(item=><a key={item.title} href={item.url} target="_blank" rel="noreferrer" onClick={()=>track("late_start_scientific_reference_open")}><span>{item.axis} · {item.year}</span><h3>{item.title}</h3><p>{item.summary}</p><small><strong>Limitação:</strong> {item.limitation}</small><footer>{item.source}<ExternalLink/></footer></a>)}</div></section>

    <section className={styles.section} id="duvidas"><header className={styles.heading}><span className={styles.eyebrow}>FAQ</span><h2>Perguntas importantes, sem previsões fáceis.</h2></header><div className={styles.faq}>{lateStartFaq.map(([question,answer],index)=><details key={question}><summary><span>{String(index+1).padStart(2,"0")}</span><strong>{question}</strong><ChevronDown/></summary><p>{answer}</p></details>)}</div></section>

    <section className={styles.related}><span className={styles.eyebrow}>Continue a leitura</span><div><Link href="/institucional/opiniao/mesma-idade-desenvolvimentos-diferentes"><strong>Leia antes</strong><span>Mesma idade. Desenvolvimentos diferentes.</span></Link><Link href="/referencias/analises/formacao-integral-do-atleta"><strong>Continue</strong><span>Formação Integral do Atleta</span></Link><Link href="/referencias/analises/modulacao-neurorespiratoria-fundismo"><strong>Aprofunde</strong><span>Respiração, cérebro e resistência</span></Link></div></section>

    <section className={styles.finalCta}><span className={styles.eyebrow}>Acesso antes da pressão</span><h2>O fundo pode começar na infância.<em>O alto rendimento não precisa começar nela.</em></h2><p>Precisamos garantir movimento, orientação, ambientes seguros e um caminho que não desapareça a cada transição.</p><div><Link href="/onze-futuro">Conheça o Onze Futuro <ArrowRight/></Link><Link href="/cadastro/onze-futuro">Cadastrar um atleta</Link><Link href="/apoie">Apoiar o ecossistema</Link><button onClick={async()=>{track("late_start_share");if(navigator.share)await navigator.share({title:document.title,url:location.href});else await navigator.clipboard.writeText(location.href)}}><Languages/> Compartilhar</button><button onClick={()=>{track("late_start_print");print()}}>Imprimir</button></div></section>
  </>;
}
