"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Activity, ArrowRight, BrainCircuit, ChevronDown, ExternalLink, HeartPulse, Languages, ShieldAlert, ShieldCheck, Sparkles, Wind } from "lucide-react";
import { ageJourney, breathingPractices, evidenceMatrix, modulationMap, myths, programLayers, respiratoryFaq, respiratoryReferences, warningSigns } from "@/lib/neurorespiratory-content";
import styles from "@/app/referencias/analises/modulacao-neurorespiratoria-fundismo/page.module.css";

function track(event: string) { window.dispatchEvent(new CustomEvent("11run:analytics", { detail: { event } })); }

export function NeurorespiratoryExperience() {
  const [progress, setProgress] = useState(0);
  const [practice, setPractice] = useState(0);
  const [layer, setLayer] = useState(0);
  const [filter, setFilter] = useState("Todos");
  const axes = useMemo(() => ["Todos", ...Array.from(new Set(respiratoryReferences.map(item => item.axis)))], []);
  const references = filter === "Todos" ? respiratoryReferences : respiratoryReferences.filter(item => item.axis === filter);

  useEffect(() => {
    track("analysis_neurorespiratory_view");
    const fired = new Set<number>();
    const onScroll = () => { const root = document.documentElement; const value = Math.min(100, Math.round(root.scrollTop / Math.max(1, root.scrollHeight - root.clientHeight) * 100)); setProgress(value); [25,50,75,90].forEach(point => { if (value >= point && !fired.has(point)) { fired.add(point); track(`analysis_neurorespiratory_${point}`); } }); };
    onScroll(); addEventListener("scroll", onScroll, { passive: true }); return () => removeEventListener("scroll", onScroll);
  }, []);

  return <>
    <div className={styles.readingProgress} aria-hidden="true"><span style={{width:`${progress}%`}} /></div>
    <section className={styles.intro} id="conceito"><div><span className={styles.eyebrow}>Antes de falar em neuromodulação</span><h2>O que significa modular o organismo pela respiração?</h2></div><div><p>“Neuromodulação respiratória” não é o nome consolidado de uma única técnica esportiva. Nesta análise, usamos o termo como conceito guarda-chuva: modificar voluntariamente o padrão respiratório e observar como isso interage com processos autonômicos, cardiovasculares, perceptivos, motores e emocionais.</p><strong>Respirar não é apertar um botão no cérebro. É interagir com um sistema complexo.</strong><small>Não se trata de estimulação direta do nervo vago, tratamento médico ou “hack” cerebral.</small></div></section>

    <section className={styles.section} id="sistema"><header className={styles.sectionHeading}><span className={styles.eyebrow}>Automático e voluntário</span><h2>Respiramos sem pensar. Mas também podemos respirar com intenção.</h2><p>A respiração é especial: mantém-se automaticamente e aceita intervenção voluntária. Essa ponte permite aprender sobre o corpo, sem transformar uma variável em explicação para tudo.</p></header><div className={styles.systemVisual} role="img" aria-label="Respiração, batimentos e passadas interagem em ritmos diferentes"><div className={styles.breathWave}><Wind /><span>Respiração</span></div><div className={styles.heartWave}><HeartPulse /><span>Batimentos</span></div><div className={styles.stepWave}><Activity /><span>Passadas</span></div></div><div className={styles.mapGrid}>{modulationMap.map(([title,text])=><article key={title}><BrainCircuit /><h3>{title}</h3><p>{text}</p></article>)}</div></section>

    <section className={styles.section} id="praticas"><header className={styles.sectionHeading}><span className={styles.eyebrow}>Cinco práticas diferentes</span><h2>Nem todo “treino respiratório” treina a mesma coisa.</h2></header><div className={styles.practiceLayout}><div className={styles.practiceTabs} role="tablist" aria-label="Práticas respiratórias">{breathingPractices.map(([title],index)=><button key={title} role="tab" aria-selected={practice===index} onClick={()=>{setPractice(index);track("analysis_breathing_practice")}}><span>0{index+1}</span>{title}</button>)}</div><article className={styles.practicePanel} role="tabpanel"><Wind /><span>{breathingPractices[practice][2]}</span><h3>{breathingPractices[practice][0]}</h3><p>{breathingPractices[practice][1]}</p><small>Objetivo, risco e necessidade de supervisão mudam conforme a prática.</small></article></div></section>

    <section className={styles.section} id="evidencias"><header className={styles.sectionHeading}><span className={styles.eyebrow}>Matriz científica</span><h2>Possibilidades existem. Promessas automáticas, não.</h2><p>A evidência mais consistente está na força dos músculos respiratórios. Transferência para desempenho, crianças e diferentes níveis esportivos continua variável.</p></header><div className={styles.matrix} role="region" aria-label="Matriz científica de estratégias respiratórias" tabIndex={0}><table><thead><tr><th>Estratégia</th><th>O que a ciência sustenta</th><th>Performance</th><th>Crianças</th><th>Parecer 11RUN</th></tr></thead><tbody>{evidenceMatrix.map(item=><tr key={item.strategy}><th>{item.strategy}</th><td>{item.science}</td><td>{item.performance}</td><td>{item.children}</td><td><strong>{item.verdict}</strong></td></tr>)}</tbody></table></div><blockquote>Respirar devagar modifica o ritmo do sistema. Não garante desempenho.</blockquote></section>

    <section className={styles.splitSection} id="hrv"><article><span className={styles.eyebrow}>Respiração lenta e HRV</span><h2>O gráfico precisa de contexto.</h2><p>Respiração lenta pode aumentar agudamente oscilações da frequência cardíaca e o acoplamento cardiorrespiratório. A própria respiração influencia a medida: HRV não é leitura direta de “força mental”, ansiedade ou prontidão.</p><ul><li>Comparar o atleta apenas com seu histórico.</li><li>Padronizar horário, posição e respiração.</li><li>Usar como apoio educativo, não classificação.</li></ul></article><article><span className={styles.eyebrow}>Treinamento inspiratório</span><h2>Respirar também exige trabalho muscular.</h2><p>Dispositivos de resistência podem melhorar força inspiratória e beneficiar alguns testes de endurance. Isso não garante aumento de VO₂ máximo ou melhora de tempo para qualquer corredor.</p><ul><li>Não é o mesmo que “respirar fundo”.</li><li>Depende de avaliação, dose e supervisão.</li><li>Em crianças, a evidência ainda é muito inicial.</li></ul></article></section>

    <section className={styles.section} id="corrida"><header className={styles.sectionHeading}><span className={styles.eyebrow}>Durante a corrida</span><h2>O corpo muda a respiração conforme a intensidade.</h2><p>Respiração nasal pode apoiar consciência em intensidade leve. Quando a demanda aumenta, transitar para respiração oronasal é normal. Nenhuma via deve ser imposta como prova de disciplina.</p></header><div className={styles.intensity}><div><span>Leve</span><i style={{width:"28%"}}/><p>Conversa confortável; observar sem controlar.</p></div><div><span>Moderada</span><i style={{width:"60%"}}/><p>Fala encurta; ventilação aumenta naturalmente.</p></div><div><span>Intensa</span><i style={{width:"94%"}}/><p>Alta demanda; respiração oronasal é esperada.</p></div></div><p className={styles.notice}><Activity /> Sincronizar passos e respiração pode ser uma atividade de percepção rítmica, nunca uma regra biomecânica universal.</p></section>

    <section className={styles.alertSection} id="seguranca"><ShieldAlert /><div><span className={styles.eyebrow}>Segurança primeiro</span><h2>Nem toda falta de ar se resolve respirando devagar.</h2><p>Cansaço esperado e sintoma incomum não são a mesma coisa. A atividade deve ser interrompida e um adulto responsável avisado diante de sinais de alerta.</p></div><div className={styles.warningGrid}>{warningSigns.map(sign=><p key={sign}>{sign}</p>)}</div><strong>Asma, broncoconstrição e obstrução laríngea induzida pelo exercício exigem avaliação profissional. Garganta fechando não deve ser atribuída automaticamente à ansiedade.</strong></section>

    <section className={styles.section} id="mitos"><header className={styles.sectionHeading}><span className={styles.eyebrow}>Mitos frequentes</span><h2>Explicações simples não precisam ser simplistas.</h2></header><div className={styles.mythGrid}>{myths.map(([myth,fact])=><article key={myth}><span>Mito</span><h3>{myth}</h3><p>{fact}</p></article>)}</div></section>

    <section className={styles.section} id="programa"><header className={styles.sectionHeading}><span className={styles.eyebrow}>Onze Futuro</span><h2>Respiração, percepção e autorregulação 11RUN.</h2><p>A prioridade inicial não é provar ganho de performance. É ensinar o jovem a perceber, compreender, comunicar e respeitar o que o organismo está dizendo.</p></header><div className={styles.layerNav} role="tablist">{programLayers.map((item,index)=><button key={item.title} role="tab" aria-selected={layer===index} onClick={()=>{setLayer(index);track("analysis_breathing_layer")}}><span>{item.level}</span>{item.title}</button>)}</div><article className={styles.layerPanel} role="tabpanel"><span>{programLayers[layer].scope}</span><h3>{programLayers[layer].title}</h3><p>{programLayers[layer].description}</p><ShieldCheck /></article><div className={styles.ageJourney}>{ageJourney.map(([age,title,text])=><article key={age}><span>{age}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>

    <section className={styles.responsibility}><div><span className={styles.eyebrow}>Tecnologia e IA</span><h2>Apoio educativo, nunca diagnóstico.</h2><p>A IA pode explicar termos, organizar registros e sugerir perguntas. Não pode diagnosticar asma ou EILO, interpretar HRV como estado psicológico, autorizar treino, prescrever carga, comparar crianças ou minimizar falta de ar.</p></div><div><strong>Ferramenta educativa de apoio.</strong><p>Não substitui avaliação médica, fisioterapêutica, psicológica ou orientação técnica presencial.</p></div></section>

    <section className={styles.section} id="ciencia"><header className={styles.sectionHeading}><span className={styles.eyebrow}>Biblioteca científica internacional</span><h2>Leia por eixo — sempre com as limitações visíveis.</h2></header><div className={styles.filters} aria-label="Filtrar referências">{axes.map(axis=><button key={axis} aria-pressed={filter===axis} onClick={()=>{setFilter(axis);track("analysis_neurorespiratory_filter")}}>{axis}</button>)}</div><div className={styles.referenceGrid}>{references.map(reference=><a key={reference.title} href={reference.url} target="_blank" rel="noreferrer" onClick={()=>track("analysis_neurorespiratory_reference")}><span>{reference.axis} · {reference.type} · {reference.year}</span><h3>{reference.title}</h3><p>{reference.summary}</p><small><strong>Limitação:</strong> {reference.limitation}</small><footer>{reference.authors}<ExternalLink /></footer></a>)}</div></section>

    <section className={styles.verdict}><Sparkles /><span className={styles.eyebrow}>Parecer científico 11RUN</span><blockquote>A respiração é uma via legítima de interação entre comportamento voluntário e processos automáticos. Em crianças e jovens fundistas, a aplicação mais responsável não é criar promessas de performance, mas desenvolver educação respiratória, percepção corporal, comunicação de sintomas e autorregulação.</blockquote><p>Intervenções com carga ou finalidade clínica exigem avaliação e supervisão profissional.</p></section>

    <section className={styles.section} id="duvidas"><header className={styles.sectionHeading}><span className={styles.eyebrow}>FAQ científico</span><h2>Respostas sem atalhos fisiológicos.</h2></header><div className={styles.faqList}>{respiratoryFaq.map(([question,answer],index)=><details key={question} onToggle={event=>{if(event.currentTarget.open)track("analysis_neurorespiratory_faq")}}><summary><span>{String(index+1).padStart(2,"0")}</span><strong>{question}</strong><ChevronDown /></summary><p>{answer}</p></details>)}</div></section>

    <section className={styles.related}><div><span className={styles.eyebrow}>Análise relacionada</span><h2>Formação Integral do Atleta</h2><p>Educação, autonomia, pensamento crítico e projeto de vida fazem parte do desenvolvimento esportivo.</p></div><Link href="/referencias/analises/formacao-integral-do-atleta">Ler análise <ArrowRight /></Link></section>

    <section className={styles.finalCta}><Wind /><span className={styles.eyebrow}>Ciência antes da promessa</span><h2>Ensinar uma criança a respirar não é mandar que ela controle o corpo.</h2><p>É ajudá-la a perceber, compreender, comunicar e respeitar o que o organismo está dizendo.</p><div><Link href="/onze-futuro">Conheça o Onze Futuro <ArrowRight /></Link><Link href="/cadastro/onze-futuro">Cadastrar um atleta</Link><Link href="/apoie">Apoiar o desenvolvimento científico</Link><button onClick={async()=>{track("analysis_neurorespiratory_share");if(navigator.share)await navigator.share({title:document.title,url:location.href});else await navigator.clipboard.writeText(location.href)}}><Languages /> Compartilhar</button></div></section>
  </>;
}
