"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { ArrowRight, Check, CircleHelp, Database, Flame, HeartPulse, Medal, Orbit, RefreshCcw, Rocket, Route, Share2, Sparkles, Star, Target, Timer, Trophy, X } from "lucide-react";
import { formatDuration, parseDuration } from "@/lib/running-formulas";
import type { PathwayInput } from "@/lib/olympic-pathway/core";
import styles from "@/app/referencias/calculadoras/chance-olimpica/chance-olimpica.module.css";

type Badge={key:string;label:string;description:string;level:"bronze"|"silver"|"gold"};
type Result = { analysis: { compatibility: number | null; potentialScore:number|null; potentialBand:string|null; confidence: string; mode: string; comparableSources: number; totalSources: number; bestInternational:{key:string;label:string;position:number}|null; internationalHighlights:Array<{key:string;label:string;position:number}>; nationalTop50:Array<{key:string;label:string;position:number}>; projectionUsed:boolean; projectionBasis:string; developmentBonus:number; youngEndurance:{active:boolean;bonus:number;floor:number;event:number;age:number}; worldTop50:Array<{position:number;performanceMs:number}>; badges:Badge[]; comparisons: Array<{ key:string; label:string; category:string; alignment:string; sourceUrl:string; status:string; message?:string; position:number|null; beyondAvailableList?:boolean; count:number; leaderMs?:number; tenthMs?:number|null; top10GapMs:number|null; updatedAt?:string|null }>; cycles:Array<{year:number;age:number}>; threeKRoutes:Array<{distance:number;riegelSeconds:number;danielsSeconds:number;divergencePercent:number}>; metadata:{engineVersion:string;generatedAt:string;rankingSnapshot:string} }; limitations:string[]; narrative:{title:string;text:string} };
const initial: PathwayInput = { event:1500, performance:"4:32.8", ageYears:13, ageMonths:4, gender:"F", representedCountry:"BR", performanceDate:"2026-07-12", context:"official", surface:"outdoor" };
const stages = ["Aquecendo o motor olímpico...","Pensando na sua próxima fase...","Pesquisando atletas e referências olímpicas...","Analisando crianças da sua idade no mundo...","Explorando rankings nacionais...","Viajando por EUA, Japão e Noruega...","Calculando coeficientes de desenvolvimento...","Procurando Top 50, Top 30 e pódios...","Desbloqueando selos e conquistas...","Preparando a grande revelação!"];
const alignmentLabel:Record<string,string>={exact_age:"idade exata",one_year_band:"faixa de um ano",two_year_band:"faixa de dois anos",school_year_reference:"série escolar aproximada",u18_broad:"categoria Sub-18 ampla",u20_broad:"categoria Sub-20 ampla",senior:"categoria adulta",projected_event:"prova projetada",insufficient_comparison:"comparação insuficiente"};
const badgeIcons:Record<string,typeof Trophy>={"young-endurance":HeartPulse,"national-top-50":Flame,"international-top-30":Target,"international-top-10":Medal,"international-top-3":Trophy,"multiple-countries":Rocket,consistent:Star,"future-cycles":Flame};

export function OlympicPathwayCalculator(){
  const [input,setInput]=useState(initial); const [step,setStep]=useState(1); const [loading,setLoading]=useState(false); const [loadingStage,setLoadingStage]=useState(0); const [result,setResult]=useState<Result|null>(null); const [showResultModal,setShowResultModal]=useState(false); const [gameOpen,setGameOpen]=useState(false); const [shareStatus,setShareStatus]=useState(""); const [error,setError]=useState(""); const resultRef=useRef<HTMLHeadingElement>(null); const modalTitleRef=useRef<HTMLHeadingElement>(null);
  const seconds=useMemo(()=>parseDuration(input.performance),[input.performance]);
  function update<K extends keyof PathwayInput>(key:K,value:PathwayInput[K]){setInput(current=>({...current,[key]:value}));setError("");}
  useEffect(()=>{const sync=()=>{if(window.location.hash==="#analisar")setGameOpen(true);};sync();window.addEventListener("hashchange",sync);return()=>window.removeEventListener("hashchange",sync);},[]);
  useEffect(()=>{if(!showResultModal&&!gameOpen&&!loading)return;const previous=document.body.style.overflow;const close=(event:KeyboardEvent)=>{if(event.key!=="Escape")return;if(showResultModal)setShowResultModal(false);else if(!loading)setGameOpen(false);};document.body.style.overflow="hidden";window.addEventListener("keydown",close);if(showResultModal)setTimeout(()=>modalTitleRef.current?.focus(),0);return()=>{document.body.style.overflow=previous;window.removeEventListener("keydown",close);};},[showResultModal,gameOpen,loading]);
  useEffect(()=>{if(!loading){setLoadingStage(0);return;}const timer=window.setInterval(()=>setLoadingStage(value=>Math.min(value+1,stages.length-1)),650);return()=>window.clearInterval(timer);},[loading]);
  async function analyze(){setLoading(true);setError("");setResult(null);setShowResultModal(false);const started=Date.now();try{const response=await fetch("/api/references/olympic-pathway",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(input)});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Não foi possível concluir a análise.");await new Promise(resolve=>setTimeout(resolve,Math.max(0,4200-(Date.now()-started))));setResult(payload);setGameOpen(false);setShowResultModal(true);}catch(reason){setError(reason instanceof Error?reason.message:"Não foi possível concluir a análise.");}finally{setLoading(false);}}
  function closeGame(){setGameOpen(false);if(window.location.hash==="#analisar")history.replaceState(null,"",window.location.pathname+window.location.search);}
  function restart(){setShowResultModal(false);setResult(null);setStep(1);setShareStatus("");setGameOpen(true);history.replaceState(null,"","#analisar");}
  async function share(){const url=`${window.location.origin}/referencias/calculadoras/chance-olimpica`;const data={title:"Probabilidade Olímpica Recreativa 11RUN",text:"Qual seria a sua probabilidade olímpica recreativa? Eu joguei a experiência da 11RUN — agora é sua vez de desbloquear conquistas!",url};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(`${data.text} ${url}`);setShareStatus("Convite copiado!");}}catch{setShareStatus("Compartilhamento cancelado.");}}
  if(loading)return <div className={styles.gameBackdrop}><section className={styles.processing} aria-live="polite"><div className={styles.intelligence}><Orbit/><strong>{Math.round((loadingStage+1)/stages.length*100)}%</strong><i/><i/><i/></div><span>Missão olímpica em andamento</span><h2>{stages[loadingStage]}</h2><div className={styles.loadingBar}><span style={{width:`${(loadingStage+1)/stages.length*100}%`}}/></div><ol>{stages.map((label,index)=><li key={label} className={index<loadingStage?styles.done:index===loadingStage?styles.active:""}>{index<loadingStage?<Check/>:index===loadingStage?<Sparkles/>:<Orbit/>}{label}</li>)}</ol><p>Estamos cruzando as bases disponíveis e montando sua experiência recreativa.</p></section></div>;
  return <>
    <div id="analisar" className={styles.gameAnchor}/>
    {gameOpen?<div className={styles.gameBackdrop} role="presentation"><section className={`${styles.calculator} ${styles.gameDialog}`} role="dialog" aria-modal="true" aria-label={`Fase ${step} de 3`}><button type="button" className={styles.gameClose} onClick={closeGame} aria-label="Sair do jogo"><X/></button><header><span className={styles.eyebrow}>Missão em três fases · nenhum cadastro obrigatório</span><h2>{step===1?"Sua marca entra na pista.":step===2?"Escolha seu mapa mundial.":"Tudo pronto para o lançamento."}</h2><p>{step===1?"Primeiro, conte qual foi o seu desafio.":step===2?"Agora vamos encontrar as comparações certas.":"Confira os dados e desbloqueie seu placar."}</p></header><div className={styles.questProgress}><span style={{width:`${step/3*100}%`}}/><b>Fase {step} de 3</b></div><div className={styles.stepper}>{[[Timer,"Sua marca"],[Target,"Mapa mundial"],[Rocket,"Lançamento"]].map(([Icon,label],index)=><button type="button" onClick={()=>setStep(index+1)} className={step===index+1?styles.current:""} key={String(label)}><i><Icon size={14}/></i>{String(label)}{step>index+1?<Check size={14}/>:null}</button>)}</div>
      <div className={styles.formPanel}>
        {step===1?<div className={styles.formGrid}><label><span>Prova</span><select value={input.event} onChange={e=>update("event",Number(e.target.value) as PathwayInput["event"])}>{[800,1000,1500,3000,5000,10000].map(value=><option value={value} key={value}>{value.toLocaleString("pt-BR")} m</option>)}</select>{input.event===1000?<small>Índice aproximado pela equivalência entre 800 m e 1.500 m.</small>:null}</label><label><span>Tempo</span><input value={input.performance} onChange={e=>update("performance",e.target.value)} inputMode="decimal" placeholder="4:32.8"/><small>mm:ss, centésimos ou hh:mm:ss</small></label><label><span>Idade em anos</span><input type="number" min="9" max="80" value={input.ageYears} onChange={e=>update("ageYears",Number(e.target.value))}/></label><label><span>Meses</span><input type="number" min="0" max="11" value={input.ageMonths} onChange={e=>update("ageMonths",Number(e.target.value))}/></label></div>:null}
        {step===2?<div className={styles.formGrid}><label><span>Categoria competitiva</span><select value={input.gender} onChange={e=>update("gender",e.target.value as "M"|"F")}><option value="F">Feminino</option><option value="M">Masculino</option></select><small>Os rankings oficiais usam categorias separadas.</small></label><label><span>País representado</span><select value={input.representedCountry} onChange={e=>update("representedCountry",e.target.value)}><option value="BR">Brasil</option><option value="US">Estados Unidos</option><option value="JP">Japão</option><option value="NO">Noruega</option><option value="KE">Quênia</option><option value="UG">Uganda</option><option value="OTHER">Outro país</option></select></label><label><span>Data da marca</span><input type="date" value={input.performanceDate} onChange={e=>update("performanceDate",e.target.value)}/></label><label><span>Tipo da marca</span><select value={input.context} onChange={e=>update("context",e.target.value as PathwayInput["context"])}><option value="official">Competição oficial</option><option value="measured-test">Teste de pista aferido</option><option value="track-training">Treino em pista</option><option value="road">Prova de rua</option><option value="free-course">Percurso livre</option><option value="estimate">Estimativa</option></select></label><label><span>Superfície</span><select value={input.surface} onChange={e=>update("surface",e.target.value as PathwayInput["surface"])}><option value="outdoor">Pista outdoor</option><option value="indoor">Pista indoor</option><option value="road">Rua</option><option value="cross">Cross country</option><option value="unmeasured">Percurso não aferido</option></select></label></div>:null}
        {step===3?<div className={styles.confirm}><Rocket/><span>Pronto para lançar?</span><h3>{input.event.toLocaleString("pt-BR")} m em {seconds?formatDuration(seconds,true):input.performance}</h3><p>{input.gender==="F"?"Feminino":"Masculino"} · {input.ageYears} anos e {input.ageMonths} meses · {input.representedCountry}</p><p>{input.context==="official"?"competição oficial":input.context} · {input.surface} · {new Date(`${input.performanceDate}T12:00:00`).toLocaleDateString("pt-BR")}</p><small>Seu placar recreativo cruza a marca informada com as referências disponíveis agora.</small></div>:null}
        {error?<p className={styles.error} role="alert">{error}</p>:null}<footer>{step>1?<button type="button" className={styles.secondary} onClick={()=>setStep(value=>value-1)}>Voltar</button>:<span/>}{step<3?<button type="button" onClick={()=>setStep(value=>value+1)}>Continuar <ArrowRight/></button>:<button type="button" onClick={analyze}>Cruzar minha marca com o mundo <Sparkles/></button>}</footer>
      </div>
    </section></div>:null}
    {result&&showResultModal?<div className={styles.modalBackdrop} role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setShowResultModal(false);}}><section className={styles.resultModal} role="dialog" aria-modal="true" aria-labelledby="result-modal-title"><button type="button" className={styles.modalClose} onClick={()=>setShowResultModal(false)} aria-label="Fechar resultado"><X/></button><div className={styles.unlockIcon}><Trophy/></div><span className={styles.eyebrow}>Placar desbloqueado!</span><h2 id="result-modal-title" ref={modalTitleRef} tabIndex={-1}>{result.analysis.potentialScore===null?"—":`${result.analysis.potentialScore}%`}</h2><strong>{result.narrative.title}</strong><p>{result.narrative.text}</p>{result.analysis.badges.length?<div className={styles.modalBadges}>{result.analysis.badges.slice(0,3).map(badge=>{const Icon=badgeIcons[badge.key]??Star;return <span key={badge.key} data-level={badge.level}><Icon/>{badge.label}</span>;})}</div>:null}<div className={styles.modalMetrics}><span>Energia do placar<strong>{result.analysis.confidence}</strong></span><span>Mundos explorados<strong>{result.analysis.comparableSources} de {result.analysis.totalSources}</strong></span><span>Modo de jogo<strong>{result.analysis.mode==="base-protegida"?"Descoberta":result.analysis.mode==="desenvolvimento"?"Evolução":"Competitivo"}</strong></span></div>{result.analysis.mode==="base-protegida"?<small><Sparkles/> Você está só no começo: celebre a evolução, divirta-se e continue descobrindo o que pode construir.</small>:null}<div className={styles.modalActions}><button type="button" onClick={()=>{setShowResultModal(false);setTimeout(()=>{resultRef.current?.scrollIntoView({behavior:"smooth",block:"start"});resultRef.current?.focus();},0);}}>Explorar meu mapa <ArrowRight/></button><button type="button" onClick={restart}><RefreshCcw/>Jogar de novo</button></div></section></div>:null}
    {result?<section className={styles.results} aria-live="polite"><header><div><span className={styles.eyebrow}>Seu Placar de Potencial</span><h2 ref={resultRef} tabIndex={-1}>{result.analysis.potentialScore===null?"—":`${result.analysis.potentialScore}%`}</h2><strong>{result.narrative.title}</strong><p>{result.narrative.text}</p></div><aside><span>Energia<strong>{result.analysis.confidence}</strong></span><span>Bases exploradas<strong>{result.analysis.comparableSources} de {result.analysis.totalSources}</strong></span><span>Motor<strong>{result.analysis.metadata.engineVersion}</strong></span><span>Atualizado<strong>{new Date(result.analysis.metadata.generatedAt).toLocaleString("pt-BR")}</strong></span></aside></header>
      {result.analysis.badges.length?<section className={styles.achievements}><div><span className={styles.eyebrow}>Conquistas desbloqueadas</span><h3>Seu inventário de jornada.</h3></div><div>{result.analysis.badges.map(badge=>{const Icon=badgeIcons[badge.key]??Star;return <article key={badge.key} data-level={badge.level}><Icon/><span>{badge.level}</span><strong>{badge.label}</strong><p>{badge.description}</p></article>;})}</div></section>:null}
      {result.analysis.youngEndurance.active?<section className={styles.enduranceCare}><HeartPulse/><div><span className={styles.eyebrow}>Distância avançada para a idade</span><h3>Surpresa desbloqueada: uma pequena grande fundista!</h3><p>Correr {result.analysis.youngEndurance.event.toLocaleString("pt-BR")} m tão jovem já demonstra coragem e interesse por distâncias longas. Faça essa aventura sempre com acompanhamento de profissional qualificado, autorização do responsável e atenção a descanso, hidratação e sinais do corpo.</p></div></section>:null}
      <section className={styles.sources}><div><span className={styles.eyebrow}>Sua posição no mundo de hoje</span><h3>Cada fonte preserva sua própria categoria.</h3></div><div className={styles.sourceGrid}>{result.analysis.comparisons.map(source=><article key={source.key}><header><Database/><div><strong>{source.label}</strong><span>{source.category} · {alignmentLabel[source.alignment]}</span></div></header>{source.status==="available"?(source.position?<><b>#{source.position}</b><p>posição hipotética entre {source.count} marcas disponíveis</p><dl><div><dt>Diferença para Top 10</dt><dd>{source.top10GapMs===null?"lista com menos de 10 marcas":source.top10GapMs<=0?"dentro do Top 10":`${(source.top10GapMs/1000).toFixed(2)} s`}</dd></div><div><dt>Atualização</dt><dd>{source.updatedAt?new Date(source.updatedAt).toLocaleDateString("pt-BR"):"não informada"}</dd></div></dl></>:<div className={styles.unavailable}><CircleHelp/><p>Sua marca ficaria além das {source.count} primeiras posições disponíveis nesta base. Nenhuma posição exata foi inventada.</p></div>):<div className={styles.unavailable}><CircleHelp/><p>{source.message??"Esta referência não possui dados sincronizados suficientes."}</p></div>} {source.sourceUrl?<a href={source.sourceUrl}>Abrir ranking usado <ArrowRight/></a>:null}</article>)}</div></section>
      {result.analysis.worldTop50.length?<section className={styles.worldBenchmark}><div><span className={styles.eyebrow}>Régua mundial adulta</span><h3>As 50 marcas que definem o nível de hoje.</h3><p>Uma referência direta e realista para atletas acima de 23 anos. Estar longe desta régua não encerra a jornada: ela mostra com clareza qual é o próximo nível competitivo.</p></div><ol>{result.analysis.worldTop50.map(item=><li key={item.position}><span>#{item.position}</span><strong>{formatDuration(item.performanceMs/1000,true)}</strong></li>)}</ol></section>:null}
      <section className={styles.cycles}><div><span className={styles.eyebrow}>Mapa de fases futuras</span><h3>Quantos ciclos ainda podem entrar no jogo?</h3><p>Cada ciclo é uma nova fase possível para aprender, evoluir e surpreender.</p></div><div>{result.analysis.cycles.map((cycle,index)=><article key={cycle.year}><span>Fase {index+1}</span><Rocket/><strong>{cycle.year}</strong><span>{cycle.age} anos</span></article>)}</div></section>
      {result.analysis.threeKRoutes.length?<section className={styles.routes}><Route/><div><span className={styles.eyebrow}>3.000 m · prova de desenvolvimento</span><h3>Duas rotas olímpicas outdoor de referência.</h3><p>Os 3.000 m rasos não integram diretamente o programa olímpico outdoor adulto. Riegel e Daniels–Gilbert projetam referências para 1.500 m e 5.000 m.</p><div>{result.analysis.threeKRoutes.map(route=><span key={route.distance}><strong>{route.distance.toLocaleString("pt-BR")} m</strong>Riegel {formatDuration(route.riegelSeconds,true)} · VDOT {formatDuration(route.danielsSeconds,true)} · divergência {route.divergencePercent.toFixed(1)}%</span>)}</div></div></section>:null}
      <section className={styles.truth}><Sparkles/><div><span className={styles.eyebrow}>Mensagem da jornada</span><h3>{result.narrative.title}</h3><p>{result.narrative.text}</p></div></section><section className={styles.nextMission}><Rocket/><div><span className={styles.eyebrow}>Próxima missão</span><h3>O jogo continua fora da tela.</h3><p>Cuide da rotina, experimente novas provas e volte quando tiver uma nova marca.</p></div></section><footer className={styles.finalActions}><button type="button" onClick={restart}><RefreshCcw/>Analisar de novo</button><button type="button" onClick={share}><Share2/>Indique a um amigo</button><Link href="/meu-painel">Acompanhar evolução <ArrowRight/></Link>{shareStatus?<span role="status">{shareStatus}</span>:null}</footer>
    </section>:null}
  </>;
}
