"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { ArrowRight, Check, CircleHelp, Database, Orbit, Route, ShieldCheck, Sparkles, Timer, X } from "lucide-react";
import { formatDuration, parseDuration } from "@/lib/running-formulas";
import type { PathwayInput } from "@/lib/olympic-pathway/core";
import styles from "@/app/referencias/calculadoras/chance-olimpica/chance-olimpica.module.css";

type Result = { analysis: { compatibility: number | null; confidence: string; mode: string; comparableSources: number; totalSources: number; comparisons: Array<{ key:string; label:string; category:string; alignment:string; sourceUrl:string; status:string; message?:string; position:number|null; beyondAvailableList?:boolean; count:number; leaderMs?:number; tenthMs?:number|null; top10GapMs:number|null; updatedAt?:string|null }>; cycles:Array<{year:number;age:number}>; threeKRoutes:Array<{distance:number;riegelSeconds:number;danielsSeconds:number;divergencePercent:number}>; metadata:{engineVersion:string;generatedAt:string;rankingSnapshot:string} }; limitations:string[]; narrative:{title:string;text:string} };
const initial: PathwayInput = { event:1500, performance:"4:32.8", ageYears:13, ageMonths:4, gender:"F", representedCountry:"BR", performanceDate:"2026-07-12", context:"official", surface:"outdoor" };
const stages = ["Validando sua marca","Identificando categoria e temporada","Encontrando referências da mesma idade","Consultando rankings nacionais","Cruzando referências internacionais","Calculando sua posição hipotética","Analisando ciclos olímpicos","Construindo sua leitura de trajetória"];
const alignmentLabel:Record<string,string>={exact_age:"idade exata",one_year_band:"faixa de um ano",two_year_band:"faixa de dois anos",school_year_reference:"série escolar aproximada",u18_broad:"categoria Sub-18 ampla",u20_broad:"categoria Sub-20 ampla",senior:"categoria adulta",projected_event:"prova projetada",insufficient_comparison:"comparação insuficiente"};

export function OlympicPathwayCalculator(){
  const [input,setInput]=useState(initial); const [step,setStep]=useState(1); const [loading,setLoading]=useState(false); const [result,setResult]=useState<Result|null>(null); const [showResultModal,setShowResultModal]=useState(false); const [error,setError]=useState(""); const resultRef=useRef<HTMLHeadingElement>(null); const modalTitleRef=useRef<HTMLHeadingElement>(null);
  const seconds=useMemo(()=>parseDuration(input.performance),[input.performance]);
  function update<K extends keyof PathwayInput>(key:K,value:PathwayInput[K]){setInput(current=>({...current,[key]:value}));setError("");}
  useEffect(()=>{if(!showResultModal)return;const previous=document.body.style.overflow;const close=(event:KeyboardEvent)=>{if(event.key==="Escape")setShowResultModal(false);};document.body.style.overflow="hidden";window.addEventListener("keydown",close);setTimeout(()=>modalTitleRef.current?.focus(),0);return()=>{document.body.style.overflow=previous;window.removeEventListener("keydown",close);};},[showResultModal]);
  async function analyze(){setLoading(true);setError("");setResult(null);setShowResultModal(false);const started=Date.now();try{const response=await fetch("/api/references/olympic-pathway",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(input)});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Não foi possível concluir a análise.");await new Promise(resolve=>setTimeout(resolve,Math.max(0,1000-(Date.now()-started))));setResult(payload);setShowResultModal(true);}catch(reason){setError(reason instanceof Error?reason.message:"Não foi possível concluir a análise.");}finally{setLoading(false);}}
  if(loading)return <section className={styles.processing} aria-live="polite"><div className={styles.intelligence}><Orbit/><strong>11</strong><i/><i/><i/></div><span>Olympic Pathway Intelligence</span><h2>Consultando as bases internas e calculando sua leitura</h2><ol>{stages.map(label=><li key={label}><Check/>{label}</li>)}</ol><p>Esta tela não simula pesquisa na internet. O resultado aparece quando o servidor conclui as consultas e o cálculo determinístico.</p></section>;
  return <>
    <section className={styles.calculator} id="analisar"><header><span className={styles.eyebrow}>Análise em três etapas · nenhum cadastro obrigatório</span><h2>Sua marca, no contexto certo.</h2><p>Os dados são processados para esta análise e não são salvos automaticamente.</p></header><div className={styles.stepper}>{["Sua marca","Comparação","Confirmação"].map((label,index)=><button type="button" onClick={()=>setStep(index+1)} className={step===index+1?styles.current:""} key={label}><i>{index+1}</i>{label}</button>)}</div>
      <div className={styles.formPanel}>
        {step===1?<div className={styles.formGrid}><label><span>Prova</span><select value={input.event} onChange={e=>update("event",Number(e.target.value) as PathwayInput["event"])}>{[800,1500,3000,5000,10000].map(value=><option value={value} key={value}>{value.toLocaleString("pt-BR")} m</option>)}</select></label><label><span>Tempo</span><input value={input.performance} onChange={e=>update("performance",e.target.value)} inputMode="decimal" placeholder="4:32.8"/><small>mm:ss, centésimos ou hh:mm:ss</small></label><label><span>Idade em anos</span><input type="number" min="9" max="80" value={input.ageYears} onChange={e=>update("ageYears",Number(e.target.value))}/></label><label><span>Meses</span><input type="number" min="0" max="11" value={input.ageMonths} onChange={e=>update("ageMonths",Number(e.target.value))}/></label></div>:null}
        {step===2?<div className={styles.formGrid}><label><span>Categoria competitiva</span><select value={input.gender} onChange={e=>update("gender",e.target.value as "M"|"F")}><option value="F">Feminino</option><option value="M">Masculino</option></select><small>Os rankings oficiais usam categorias separadas.</small></label><label><span>País representado</span><select value={input.representedCountry} onChange={e=>update("representedCountry",e.target.value)}><option value="BR">Brasil</option><option value="US">Estados Unidos</option><option value="JP">Japão</option><option value="NO">Noruega</option><option value="KE">Quênia</option><option value="UG">Uganda</option><option value="OTHER">Outro país</option></select></label><label><span>Data da marca</span><input type="date" value={input.performanceDate} onChange={e=>update("performanceDate",e.target.value)}/></label><label><span>Tipo da marca</span><select value={input.context} onChange={e=>update("context",e.target.value as PathwayInput["context"])}><option value="official">Competição oficial</option><option value="measured-test">Teste de pista aferido</option><option value="track-training">Treino em pista</option><option value="road">Prova de rua</option><option value="free-course">Percurso livre</option><option value="estimate">Estimativa</option></select></label><label><span>Superfície</span><select value={input.surface} onChange={e=>update("surface",e.target.value as PathwayInput["surface"])}><option value="outdoor">Pista outdoor</option><option value="indoor">Pista indoor</option><option value="road">Rua</option><option value="cross">Cross country</option><option value="unmeasured">Percurso não aferido</option></select></label></div>:null}
        {step===3?<div className={styles.confirm}><ShieldCheck/><span>Confirme a leitura</span><h3>{input.event.toLocaleString("pt-BR")} m em {seconds?formatDuration(seconds,true):input.performance}</h3><p>{input.gender==="F"?"Feminino":"Masculino"} · {input.ageYears} anos e {input.ageMonths} meses · {input.representedCountry}</p><p>{input.context==="official"?"competição oficial":input.context} · {input.surface} · {new Date(`${input.performanceDate}T12:00:00`).toLocaleDateString("pt-BR")}</p><small>Ao continuar, você confirma que compreende: esta é uma análise histórica e comparativa, não uma previsão individual.</small></div>:null}
        {error?<p className={styles.error} role="alert">{error}</p>:null}<footer>{step>1?<button type="button" className={styles.secondary} onClick={()=>setStep(value=>value-1)}>Voltar</button>:<span/>}{step<3?<button type="button" onClick={()=>setStep(value=>value+1)}>Continuar <ArrowRight/></button>:<button type="button" onClick={analyze}>Cruzar minha marca com o mundo <Sparkles/></button>}</footer>
      </div>
    </section>
    {result&&showResultModal?<div className={styles.modalBackdrop} role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setShowResultModal(false);}}><section className={styles.resultModal} role="dialog" aria-modal="true" aria-labelledby="result-modal-title"><button type="button" className={styles.modalClose} onClick={()=>setShowResultModal(false)} aria-label="Fechar resultado"><X/></button><span className={styles.eyebrow}>Sua leitura está pronta</span><h2 id="result-modal-title" ref={modalTitleRef} tabIndex={-1}>{result.analysis.compatibility===null?"Dados insuficientes":`${result.analysis.compatibility}%`}</h2><strong>{result.analysis.compatibility===null?"Ainda não há bases suficientes para um índice responsável":"de compatibilidade histórica"}</strong><p>{result.analysis.compatibility===null?"Nenhum percentual foi produzido. Consulte as limitações e as fontes disponíveis.":"Este número compara sua marca com referências atuais. Ele não representa a probabilidade de participar dos Jogos Olímpicos."}</p><div className={styles.modalMetrics}><span>Confiança<strong>{result.analysis.confidence}</strong></span><span>Bases comparáveis<strong>{result.analysis.comparableSources} de {result.analysis.totalSources}</strong></span><span>Modo<strong>{result.analysis.mode==="base-protegida"?"Base Protegida":result.analysis.mode==="desenvolvimento"?"Desenvolvimento":"Rota Competitiva"}</strong></span></div>{result.analysis.mode==="base-protegida"?<small><ShieldCheck/> Seu valor não muda com esse número. Ele mostra uma marca hoje, não define o futuro.</small>:null}<div className={styles.modalActions}><button type="button" onClick={()=>{setShowResultModal(false);setTimeout(()=>{resultRef.current?.scrollIntoView({behavior:"smooth",block:"start"});resultRef.current?.focus();},0);}}>Ver análise completa <ArrowRight/></button><button type="button" onClick={()=>setShowResultModal(false)}>Fechar</button></div></section></div>:null}
    {result?<section className={styles.results} aria-live="polite"><header><div><span className={styles.eyebrow}>Resposta principal · análise histórica</span><h2 ref={resultRef} tabIndex={-1}>{result.analysis.compatibility===null?"Dados insuficientes":`${result.analysis.compatibility}%`}</h2><strong>{result.analysis.compatibility===null?"Probabilidade individual ainda não calibrada":"de compatibilidade histórica com referências de alto rendimento"}</strong><p>{result.analysis.compatibility===null?"As bases atuais não permitem produzir um índice responsável para esta combinação.":"Isso não significa a mesma porcentagem de probabilidade de participar dos Jogos Olímpicos."}</p></div><aside><span>Confiança<strong>{result.analysis.confidence}</strong></span><span>Dados comparáveis<strong>{result.analysis.comparableSources} de {result.analysis.totalSources}</strong></span><span>Modelo<strong>{result.analysis.metadata.engineVersion}</strong></span><span>Atualizado<strong>{new Date(result.analysis.metadata.generatedAt).toLocaleString("pt-BR")}</strong></span></aside></header>
      {result.analysis.mode==="base-protegida"?<div className={styles.protected}><ShieldCheck/><div><strong>Modo Base Protegida</strong><p>Nesta idade, crescimento, maturação e experiências esportivas podem alterar profundamente uma trajetória. O resultado mostra onde a marca está hoje, não quem a criança será no futuro.</p><b>Seu valor não muda com esse número.</b></div></div>:null}
      <section className={styles.sources}><div><span className={styles.eyebrow}>Sua posição no mundo de hoje</span><h3>Cada fonte preserva sua própria categoria.</h3></div><div className={styles.sourceGrid}>{result.analysis.comparisons.map(source=><article key={source.key}><header><Database/><div><strong>{source.label}</strong><span>{source.category} · {alignmentLabel[source.alignment]}</span></div></header>{source.status==="available"?(source.position?<><b>#{source.position}</b><p>posição hipotética entre {source.count} marcas disponíveis</p><dl><div><dt>Diferença para Top 10</dt><dd>{source.top10GapMs===null?"lista com menos de 10 marcas":source.top10GapMs<=0?"dentro do Top 10":`${(source.top10GapMs/1000).toFixed(2)} s`}</dd></div><div><dt>Atualização</dt><dd>{source.updatedAt?new Date(source.updatedAt).toLocaleDateString("pt-BR"):"não informada"}</dd></div></dl></>:<div className={styles.unavailable}><CircleHelp/><p>Sua marca ficaria além das {source.count} primeiras posições disponíveis nesta base. Nenhuma posição exata foi inventada.</p></div>):<div className={styles.unavailable}><CircleHelp/><p>{source.message??"Esta referência não possui dados sincronizados suficientes."}</p></div>} {source.sourceUrl?<a href={source.sourceUrl}>Abrir ranking usado <ArrowRight/></a>:null}</article>)}</div></section>
      <section className={styles.cycles}><div><span className={styles.eyebrow}>Tempo e maturidade</span><h3>Próximos ciclos, sem contagem regressiva.</h3><p>A idade menor aumenta o tempo disponível para desenvolvimento, não a probabilidade automática.</p></div><div>{result.analysis.cycles.map(cycle=><article key={cycle.year}><Timer/><strong>{cycle.year}</strong><span>{cycle.age} anos</span></article>)}</div></section>
      {result.analysis.threeKRoutes.length?<section className={styles.routes}><Route/><div><span className={styles.eyebrow}>3.000 m · prova de desenvolvimento</span><h3>Duas rotas olímpicas outdoor de referência.</h3><p>Os 3.000 m rasos não integram diretamente o programa olímpico outdoor adulto. Riegel e Daniels–Gilbert projetam referências para 1.500 m e 5.000 m.</p><div>{result.analysis.threeKRoutes.map(route=><span key={route.distance}><strong>{route.distance.toLocaleString("pt-BR")} m</strong>Riegel {formatDuration(route.riegelSeconds,true)} · VDOT {formatDuration(route.danielsSeconds,true)} · divergência {route.divergencePercent.toFixed(1)}%</span>)}</div></div></section>:null}
      <section className={styles.truth}><ShieldCheck/><div><span className={styles.eyebrow}>Leitura responsável</span><h3>{result.narrative.title}</h3><p>{result.narrative.text}</p><ul>{result.limitations.map(item=><li key={item}>{item}</li>)}</ul></div></section><footer className={styles.finalActions}><button type="button" onClick={()=>{setResult(null);setStep(1);document.querySelector("#analisar")?.scrollIntoView({behavior:"smooth"});}}>Comparar outra marca</button><Link href="/meu-painel">Acompanhar minha evolução <ArrowRight/></Link></footer>
    </section>:null}
  </>;
}
