"use client";
/* eslint-disable @next/next/no-img-element -- a prévia usa uma URL blob gerada no navegador */

import { useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { ArrowRight, Check, CircleHelp, Database, Download, Flame, HeartPulse, Image as ImageIcon, LoaderCircle, Medal, Orbit, RefreshCcw, Rocket, Route, Share2, Sparkles, Star, Target, Timer, Trophy, X } from "lucide-react";
import { formatDuration, parseDuration } from "@/lib/running-formulas";
import type { PathwayInput } from "@/lib/olympic-pathway/core";
import styles from "@/app/referencias/calculadoras/chance-olimpica/chance-olimpica.module.css";

type Badge={key:string;label:string;description:string;level:"bronze"|"silver"|"gold"};
type Result = { analysis: { compatibility: number | null; potentialScore:number|null; potentialBand:string|null; confidence: string; mode: string; comparableSources: number; totalSources: number; bestInternational:{key:string;label:string;position:number}|null; internationalHighlights:Array<{key:string;label:string;position:number}>; nationalTop50:Array<{key:string;label:string;position:number}>; projectionUsed:boolean; projectionBasis:string; developmentBonus:number; youngEndurance:{active:boolean;bonus:number;floor:number;event:number;age:number}; worldTop50:Array<{position:number;performanceMs:number}>; badges:Badge[]; comparisons: Array<{ key:string; label:string; category:string; alignment:string; sourceUrl:string; status:string; message?:string; position:number|null; beyondAvailableList?:boolean; count:number; leaderMs?:number; tenthMs?:number|null; top10GapMs:number|null; updatedAt?:string|null }>; cycles:Array<{year:number;age:number}>; threeKRoutes:Array<{distance:number;riegelSeconds:number;danielsSeconds:number;divergencePercent:number}>; metadata:{engineVersion:string;generatedAt:string;rankingSnapshot:string} }; limitations:string[]; narrative:{title:string;text:string} };
const initial: PathwayInput = { event:1500, performance:"4:32.8", ageYears:13, ageMonths:4, gender:"F", representedCountry:"BR", performanceDate:"2026-07-12", context:"official", surface:"outdoor" };
const stages = ["Aquecendo o motor olímpico...","Pensando na sua próxima fase...","Pesquisando atletas e referências olímpicas...","Analisando crianças da sua idade no mundo...","Explorando rankings nacionais...","Viajando por EUA, Japão e Noruega...","Calculando coeficientes de desenvolvimento...","Procurando Top 50, Top 30 e pódios...","Desbloqueando selos e conquistas...","Preparando a grande revelação!"];
const loadingStageDurationMs=1050;
const minimumMissionDurationMs=11000;
const phaseHelp=[
  {title:"Como informar sua marca",text:"Escolha a distância realizada e preencha o tempo em três partes. O jogo monta o formato oficial automaticamente.",items:["Minutos: o número antes dos dois-pontos.","Segundos: de 00 a 59.","Centésimos: de 00 a 99. Se não souber, use 00.","Idade e meses ajudam a encontrar referências da mesma fase esportiva."]},
  {title:"Como montamos seu mapa",text:"Essas respostas determinam quais rankings e coeficientes podem participar da comparação.",items:["Categoria competitiva acompanha a divisão das fontes oficiais.","País representado define o contexto principal, sem limitar a busca internacional.","Tipo e superfície ajudam a interpretar se a marca veio de competição, teste ou treino.","Nenhum desses campos homologa oficialmente um resultado."]},
  {title:"Antes do lançamento",text:"Esta é a conferência final da missão. Volte se algum dado não estiver correto.",items:["Confira distância, tempo, idade e categoria.","Ao lançar, o jogo percorre as fontes disponíveis e mostra cada etapa da busca.","O placar é recreativo e educativo: ele não substitui avaliação profissional nem seleção esportiva."]}
];
const alignmentLabel:Record<string,string>={exact_age:"idade exata",one_year_band:"faixa de um ano",two_year_band:"faixa de dois anos",school_year_reference:"série escolar aproximada",u18_broad:"categoria Sub-18 ampla",u20_broad:"categoria Sub-20 ampla",senior:"categoria adulta",projected_event:"prova projetada",insufficient_comparison:"comparação insuficiente"};
const badgeIcons:Record<string,typeof Trophy>={"young-endurance":HeartPulse,"national-top-50":Flame,"international-top-30":Target,"international-top-10":Medal,"international-top-3":Trophy,"multiple-countries":Rocket,consistent:Star,"future-cycles":Flame};

type ShareArtwork={blob:Blob;url:string;fileName:string};

function loadCanvasImage(src:string){return new Promise<HTMLImageElement>((resolve,reject)=>{const image=new window.Image();image.onload=()=>resolve(image);image.onerror=reject;image.src=src;});}
function roundedRect(context:CanvasRenderingContext2D,x:number,y:number,width:number,height:number,radius:number){context.beginPath();context.roundRect(x,y,width,height,radius);context.fill();}
function fitText(context:CanvasRenderingContext2D,text:string,maxWidth:number,startSize:number,minSize:number){let size=startSize;while(size>minSize){context.font=`700 ${size}px Arial, sans-serif`;if(context.measureText(text).width<=maxWidth)break;size-=2;}return size;}
function wrapCanvasText(context:CanvasRenderingContext2D,text:string,x:number,y:number,maxWidth:number,lineHeight:number,maxLines:number){const words=text.split(/\s+/);const lines:string[]=[];let line="";for(const word of words){const test=line?`${line} ${word}`:word;if(context.measureText(test).width>maxWidth&&line){lines.push(line);line=word;if(lines.length===maxLines-1)break;}else line=test;}if(line&&lines.length<maxLines)lines.push(line);if(lines.join(" ").length<text.length){lines[lines.length-1]=`${lines[lines.length-1].replace(/[.,;:!?]?$/,"")}…`;}lines.forEach((value,index)=>context.fillText(value,x,y+index*lineHeight));return y+lines.length*lineHeight;}

export function OlympicPathwayCalculator(){
  const [input,setInput]=useState(initial); const [athleteName,setAthleteName]=useState(""); const [step,setStep]=useState(1); const [loading,setLoading]=useState(false); const [loadingStage,setLoadingStage]=useState(0); const [result,setResult]=useState<Result|null>(null); const [showResultModal,setShowResultModal]=useState(false); const [gameOpen,setGameOpen]=useState(false); const [showPhaseHelp,setShowPhaseHelp]=useState(false); const [shareStatus,setShareStatus]=useState(""); const [shareArtwork,setShareArtwork]=useState<ShareArtwork|null>(null); const [creatingArtwork,setCreatingArtwork]=useState(false); const [error,setError]=useState(""); const resultRef=useRef<HTMLHeadingElement>(null); const modalTitleRef=useRef<HTMLHeadingElement>(null);
  const seconds=useMemo(()=>parseDuration(input.performance),[input.performance]);
  const timeParts=useMemo(()=>{const total=Math.max(0,Math.round((seconds??0)*100));return{minutes:String(Math.floor(total/6000)),seconds:String(Math.floor(total%6000/100)).padStart(2,"0"),hundredths:String(total%100).padStart(2,"0")};},[seconds]);
  function update<K extends keyof PathwayInput>(key:K,value:PathwayInput[K]){setInput(current=>({...current,[key]:value}));setError("");}
  function updateTimePart(part:"minutes"|"seconds"|"hundredths",raw:string){const digits=raw.replace(/\D/g,"");const limit=part==="minutes"?999:part==="seconds"?59:99;const next={...timeParts,[part]:String(Math.min(limit,Number(digits||0)))};update("performance",`${Number(next.minutes)}:${String(Number(next.seconds)).padStart(2,"0")}.${String(Number(next.hundredths)).padStart(2,"0")}`);}
  function advance(){if(step===1&&(!athleteName.trim()||!seconds||input.ageYears<9||input.ageYears>80||input.ageMonths<0||input.ageMonths>11)){setError(!athleteName.trim()?"Informe seu nome para personalizarmos a missão e a arte final.":!seconds?"Informe um tempo maior que zero.":"Revise a idade: de 9 a 80 anos e de 0 a 11 meses.");return;}if(step===2&&!input.performanceDate){setError("Informe a data da marca para continuar.");return;}setStep(value=>Math.min(3,value+1));}
  useEffect(()=>{const sync=()=>{if(window.location.hash==="#analisar")setGameOpen(true);};sync();window.addEventListener("hashchange",sync);return()=>window.removeEventListener("hashchange",sync);},[]);
  useEffect(()=>{if(!showResultModal&&!gameOpen&&!loading&&!shareArtwork)return;const previous=document.body.style.overflow;const close=(event:KeyboardEvent)=>{if(event.key!=="Escape")return;if(shareArtwork)setShareArtwork(null);else if(showPhaseHelp)setShowPhaseHelp(false);else if(showResultModal)setShowResultModal(false);else if(!loading)setGameOpen(false);};document.body.style.overflow="hidden";window.addEventListener("keydown",close);if(showResultModal)setTimeout(()=>modalTitleRef.current?.focus(),0);return()=>{document.body.style.overflow=previous;window.removeEventListener("keydown",close);};},[showResultModal,showPhaseHelp,gameOpen,loading,shareArtwork]);
  useEffect(()=>()=>{if(shareArtwork)URL.revokeObjectURL(shareArtwork.url);},[shareArtwork]);
  useEffect(()=>setShowPhaseHelp(false),[step]);
  useEffect(()=>{if(!loading){setLoadingStage(0);return;}const timer=window.setInterval(()=>setLoadingStage(value=>Math.min(value+1,stages.length-1)),loadingStageDurationMs);return()=>window.clearInterval(timer);},[loading]);
  async function analyze(){setLoading(true);setError("");setResult(null);setShowResultModal(false);const started=Date.now();try{const response=await fetch("/api/references/olympic-pathway",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(input)});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Não foi possível concluir a análise.");await new Promise(resolve=>setTimeout(resolve,Math.max(0,minimumMissionDurationMs-(Date.now()-started))));setResult(payload);setGameOpen(false);setShowResultModal(true);}catch(reason){setError(reason instanceof Error?reason.message:"Não foi possível concluir a análise.");}finally{setLoading(false);}}
  function closeGame(){setGameOpen(false);if(window.location.hash==="#analisar")history.replaceState(null,"",window.location.pathname+window.location.search);}
  function restart(){setShowResultModal(false);setResult(null);setStep(1);setShareStatus("");setGameOpen(true);history.replaceState(null,"","#analisar");}
  async function share(){const url=`${window.location.origin}/referencias/calculadoras/chance-olimpica`;const data={title:"Probabilidade Olímpica Recreativa 11RUN",text:"Qual seria a sua probabilidade olímpica recreativa? Eu joguei a experiência da 11RUN — agora é sua vez de desbloquear conquistas!",url};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(`${data.text} ${url}`);setShareStatus("Convite copiado!");}}catch{setShareStatus("Compartilhamento cancelado.");}}
  async function createShareArtwork(){if(!result)return;setCreatingArtwork(true);setShareStatus("");try{const canvas=document.createElement("canvas");canvas.width=1080;canvas.height=1350;const context=canvas.getContext("2d");if(!context)throw new Error("Canvas indisponível");const score=result.analysis.potentialScore===null?"—":`${result.analysis.potentialScore}%`;const event=`${input.event.toLocaleString("pt-BR")} m`;const performance=seconds?formatDuration(seconds,true):input.performance;const badge=result.analysis.badges[0]?.label??"Jornada desbloqueada";
      context.fillStyle="#151718";context.fillRect(0,0,1080,1350);context.fillStyle="#303438";context.fillRect(0,0,1080,330);context.fillStyle="#ed6509";context.fillRect(0,330,22,1020);context.fillStyle="#ed6509";context.fillRect(0,1332,1080,18);context.fillStyle="#f7f7f5";context.beginPath();context.moveTo(0,1020);context.lineTo(1080,860);context.lineTo(1080,1332);context.lineTo(0,1332);context.closePath();context.fill();
      context.strokeStyle="#ed6509";context.lineWidth=9;const olympicRings=[[760,145],[850,145],[940,145],[805,205],[895,205]];for(const [x,y] of olympicRings){context.beginPath();context.arc(x,y,58,0,Math.PI*2);context.stroke();}context.lineWidth=5;context.beginPath();context.arc(850,180,225,-.25,.74);context.stroke();
      const logo=await loadCanvasImage("/assets/branding/originais/11run-vertical-branco.png");const ratio=logo.width/logo.height;const logoWidth=245;context.drawImage(logo,72,52,logoWidth,logoWidth/ratio);
      context.fillStyle="#ed6509";context.font="700 24px Arial, sans-serif";context.letterSpacing="3px";context.fillText("MISSÃO POTENCIAL OLÍMPICO 11RUN",72,244);context.fillStyle="#ffffffc7";const participantLine=`${athleteName.trim().toUpperCase()} PARTICIPOU DA MISSÃO 11RUN`;const participantSize=fitText(context,participantLine,760,22,15);context.font=`400 ${participantSize}px Arial, sans-serif`;context.fillText(participantLine,72,285);
      context.fillStyle="#fff";context.font="300 210px Arial, sans-serif";context.fillText(score,68,555);const chanceLabel="DE CHANCES DE IR PARA AS OLIMPÍADAS";const chanceLabelSize=fitText(context,chanceLabel,900,27,20);context.font=`700 ${chanceLabelSize}px Arial, sans-serif`;context.fillStyle="#ed6509";context.fillText(chanceLabel,73,610);
      context.fillStyle="#fff";const titleSize=fitText(context,result.narrative.title,910,66,42);context.font=`700 ${titleSize}px Arial, sans-serif`;const cursor=wrapCanvasText(context,result.narrative.title,72,705,910,titleSize*1.08,2);
      context.font="400 25px Arial, sans-serif";context.fillStyle="#d7dcda";const narrativeBottom=wrapCanvasText(context,result.narrative.text,72,cursor+28,900,34,3);
      const badgeText=`★ ${badge.toUpperCase()}`;const badgeY=Math.min(962,narrativeBottom+20);const badgeFontSize=fitText(context,badgeText,760,23,16);context.font=`700 ${badgeFontSize}px Arial, sans-serif`;const badgeWidth=Math.min(840,Math.max(330,context.measureText(badgeText).width+60));context.fillStyle="#ed6509";roundedRect(context,72,badgeY,badgeWidth,62,31);context.fillStyle="#151718";context.fillText(badgeText,102,badgeY+40);
      context.fillStyle="#201d1a";context.font="700 54px Arial, sans-serif";context.fillText(`${event}  •  ${performance}`,72,1114);context.fillStyle="#6f655c";context.font="400 27px Arial, sans-serif";context.fillText(`${input.gender==="F"?"Feminino":"Masculino"}  •  ${input.ageYears} anos  •  ${result.analysis.comparableSources} mundos explorados`,74,1164);
      context.fillStyle="#292929";const personalCta=`Faça como ${athleteName.trim()} e veja onde sua marca pode sonhar.`;const personalCtaSize=fitText(context,personalCta,920,31,22);context.font=`700 ${personalCtaSize}px Arial, sans-serif`;context.fillText(personalCta,72,1226);context.fillStyle="#ed6509";context.font="700 27px Arial, sans-serif";context.fillText("11run.com.br/referencias/calculadoras/chance-olimpica",72,1272);
      const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(new Error("Falha ao gerar imagem")),"image/jpeg",.94));const fileName=`placar-11run-${input.event}m.jpg`;setShareArtwork(current=>{if(current)URL.revokeObjectURL(current.url);return{blob,url:URL.createObjectURL(blob),fileName};});
    }catch{setShareStatus("Não foi possível criar a arte agora. Tente novamente.");}finally{setCreatingArtwork(false);}}
  function shareCopy(){const score=result?.analysis.potentialScore===null?"—":`${result?.analysis.potentialScore}%`;return `${athleteName.trim()} participou da Missão Potencial Olímpico 11RUN e recebeu ${score} de chances de ir para as Olimpíadas! 🏃✨ Veja o resultado e descubra até onde a sua marca pode sonhar. Participe também: https://11run.com.br/referencias/calculadoras/chance-olimpica`;}
  async function shareGeneratedArtwork(){if(!shareArtwork)return;const file=new File([shareArtwork.blob],shareArtwork.fileName,{type:"image/jpeg"});try{if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){await navigator.share({title:"Meu Placar 11RUN",text:shareCopy(),files:[file]});setShareStatus("Arte pronta para compartilhar!");}else{await navigator.clipboard.writeText(shareCopy());const anchor=document.createElement("a");anchor.href=shareArtwork.url;anchor.download=shareArtwork.fileName;anchor.click();setShareStatus("Arte baixada e legenda copiada!");}}catch(error){if(error instanceof Error&&error.name!=="AbortError")setShareStatus("Não foi possível abrir o compartilhamento.");}}
  function downloadArtwork(){if(!shareArtwork)return;const anchor=document.createElement("a");anchor.href=shareArtwork.url;anchor.download=shareArtwork.fileName;anchor.click();setShareStatus("Arte 4:5 baixada!");}
  if(loading)return <div className={styles.gameBackdrop}><section className={styles.processing} aria-live="polite"><div className={styles.intelligence}><Orbit/><strong>{Math.round((loadingStage+1)/stages.length*100)}%</strong><i/><i/><i/></div><span>Missão olímpica em andamento</span><h2>{stages[loadingStage]}</h2><div className={styles.loadingBar}><span style={{width:`${(loadingStage+1)/stages.length*100}%`}}/></div><ol>{stages.map((label,index)=><li key={label} className={index<loadingStage?styles.done:index===loadingStage?styles.active:""}>{index<loadingStage?<Check/>:index===loadingStage?<Sparkles/>:<Orbit/>}{label}</li>)}</ol><p>Estamos cruzando as bases disponíveis e montando sua experiência recreativa.</p></section></div>;
  return <>
    <div id="analisar" className={styles.gameAnchor}/>
    {gameOpen?<div className={styles.gameBackdrop} role="presentation"><section className={`${styles.calculator} ${styles.gameDialog}`} role="dialog" aria-modal="true" aria-label={`Fase ${step} de 3`}><button type="button" className={styles.gameHelp} onClick={()=>setShowPhaseHelp(true)} aria-label={`Ajuda da fase ${step}`}><CircleHelp/></button><button type="button" className={styles.gameClose} onClick={closeGame} aria-label="Sair do jogo"><X/></button><header><span className={styles.eyebrow}>Missão em três fases · nenhum cadastro obrigatório</span><h2>{step===1?"Sua marca entra na pista.":step===2?"Escolha seu mapa mundial.":"Tudo pronto para o lançamento."}</h2><p>{step===1?"Primeiro, conte qual foi o seu desafio.":step===2?"Agora vamos encontrar as comparações certas.":"Confira os dados e desbloqueie seu placar."}</p></header><div className={styles.questProgress}><span style={{width:`${step/3*100}%`}}/><b>Fase {step} de 3</b></div><div className={styles.stepper}>{[[Timer,"Sua marca"],[Target,"Mapa mundial"],[Rocket,"Lançamento"]].map(([Icon,label],index)=><button type="button" onClick={()=>index+1<step?setStep(index+1):index+1===step+1?advance():undefined} disabled={index+1>step+1} className={step===index+1?styles.current:""} key={String(label)}><i><Icon size={14}/></i>{String(label)}{step>index+1?<Check size={14}/>:null}</button>)}</div>
      <div className={styles.formPanel}>
        {step===1?<div className={styles.formGrid}><label className={styles.fullField}><span>Seu nome</span><input type="text" autoComplete="name" maxLength={50} value={athleteName} onChange={e=>{setAthleteName(e.target.value);setError("");}} placeholder="Como podemos chamar você?"/><small>Usaremos seu nome para personalizar a missão e a arte final.</small></label><label><span>Prova</span><select value={input.event} onChange={e=>update("event",Number(e.target.value) as PathwayInput["event"])}>{[800,1000,1500,3000,5000,10000].map(value=><option value={value} key={value}>{value.toLocaleString("pt-BR")} m</option>)}</select>{input.event===1000?<small>Índice aproximado pela equivalência entre 800 m e 1.500 m.</small>:null}</label><fieldset className={styles.timeComposer}><legend>Tempo da marca</legend><div><label><span>Minutos</span><input value={timeParts.minutes} onChange={e=>updateTimePart("minutes",e.target.value)} inputMode="numeric" pattern="[0-9]*" aria-label="Minutos"/></label><b>:</b><label><span>Segundos</span><input value={timeParts.seconds} onChange={e=>updateTimePart("seconds",e.target.value)} inputMode="numeric" pattern="[0-9]*" aria-label="Segundos"/></label><b>.</b><label><span>Centésimos</span><input value={timeParts.hundredths} onChange={e=>updateTimePart("hundredths",e.target.value)} inputMode="numeric" pattern="[0-9]*" aria-label="Centésimos"/></label></div><small>Formato automático: <strong>{input.performance}</strong></small></fieldset><label><span>Idade em anos</span><input type="number" min="9" max="80" value={input.ageYears} onChange={e=>update("ageYears",Number(e.target.value))}/></label><label><span>Meses</span><input type="number" min="0" max="11" value={input.ageMonths} onChange={e=>update("ageMonths",Number(e.target.value))}/></label></div>:null}
        {step===2?<div className={styles.formGrid}><label><span>Categoria competitiva</span><select value={input.gender} onChange={e=>update("gender",e.target.value as "M"|"F")}><option value="F">Feminino</option><option value="M">Masculino</option></select><small>Os rankings oficiais usam categorias separadas.</small></label><label><span>País representado</span><select value={input.representedCountry} onChange={e=>update("representedCountry",e.target.value)}><option value="BR">Brasil</option><option value="US">Estados Unidos</option><option value="JP">Japão</option><option value="NO">Noruega</option><option value="KE">Quênia</option><option value="UG">Uganda</option><option value="OTHER">Outro país</option></select></label><label><span>Data da marca</span><input type="date" value={input.performanceDate} onChange={e=>update("performanceDate",e.target.value)}/></label><label><span>Tipo da marca</span><select value={input.context} onChange={e=>update("context",e.target.value as PathwayInput["context"])}><option value="official">Competição oficial</option><option value="measured-test">Teste de pista aferido</option><option value="track-training">Treino em pista</option><option value="road">Prova de rua</option><option value="free-course">Percurso livre</option><option value="estimate">Estimativa</option></select></label><label><span>Superfície</span><select value={input.surface} onChange={e=>update("surface",e.target.value as PathwayInput["surface"])}><option value="outdoor">Pista outdoor</option><option value="indoor">Pista indoor</option><option value="road">Rua</option><option value="cross">Cross country</option><option value="unmeasured">Percurso não aferido</option></select></label></div>:null}
        {step===3?<div className={styles.confirm}><Rocket/><span>Pronto para lançar?</span><h3>{input.event.toLocaleString("pt-BR")} m em {seconds?formatDuration(seconds,true):input.performance}</h3><p>{input.gender==="F"?"Feminino":"Masculino"} · {input.ageYears} anos e {input.ageMonths} meses · {input.representedCountry}</p><p>{input.context==="official"?"competição oficial":input.context} · {input.surface} · {new Date(`${input.performanceDate}T12:00:00`).toLocaleDateString("pt-BR")}</p><small>Sua análise de chances cruza a marca informada com as referências disponíveis agora.</small></div>:null}
        {error?<p className={styles.error} role="alert">{error}</p>:null}<footer>{step>1?<button type="button" className={styles.secondary} onClick={()=>setStep(value=>value-1)}>Voltar</button>:<span/>}{step<3?<button type="button" onClick={advance}>Continuar <ArrowRight/></button>:<button type="button" onClick={analyze}>Analisar <Sparkles/></button>}</footer>
      </div>
    </section></div>:null}
    {gameOpen&&showPhaseHelp?<div className={styles.phaseHelpBackdrop} role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setShowPhaseHelp(false);}}><section className={styles.phaseHelp} role="dialog" aria-modal="true" aria-labelledby="phase-help-title"><button type="button" onClick={()=>setShowPhaseHelp(false)} aria-label="Fechar ajuda"><X/></button><span className={styles.eyebrow}>Ajuda · fase {step} de 3</span><CircleHelp/><h2 id="phase-help-title">{phaseHelp[step-1].title}</h2><p>{phaseHelp[step-1].text}</p><ul>{phaseHelp[step-1].items.map(item=><li key={item}><Check/>{item}</li>)}</ul><button type="button" className={styles.phaseHelpAction} onClick={()=>setShowPhaseHelp(false)}>Entendi, continuar missão <ArrowRight/></button></section></div>:null}
    {result&&showResultModal?<div className={styles.modalBackdrop} role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setShowResultModal(false);}}><section className={styles.resultModal} role="dialog" aria-modal="true" aria-labelledby="result-modal-title"><button type="button" className={styles.modalClose} onClick={()=>setShowResultModal(false)} aria-label="Fechar resultado"><X/></button><div className={styles.unlockIcon}><Trophy/></div><span className={styles.eyebrow}>Placar desbloqueado!</span><h2 id="result-modal-title" ref={modalTitleRef} tabIndex={-1}>{result.analysis.potentialScore===null?"—":`${result.analysis.potentialScore}%`}</h2><strong>{result.narrative.title}</strong><p>{result.narrative.text}</p>{result.analysis.badges.length?<div className={styles.modalBadges}>{result.analysis.badges.slice(0,3).map(badge=>{const Icon=badgeIcons[badge.key]??Star;return <span key={badge.key} data-level={badge.level}><Icon/>{badge.label}</span>;})}</div>:null}<div className={styles.modalMetrics}><span>Energia do placar<strong>{result.analysis.confidence}</strong></span><span>Mundos explorados<strong>{result.analysis.comparableSources} de {result.analysis.totalSources}</strong></span><span>Modo de jogo<strong>{result.analysis.mode==="base-protegida"?"Descoberta":result.analysis.mode==="desenvolvimento"?"Evolução":"Competitivo"}</strong></span></div>{result.analysis.mode==="base-protegida"?<small><Sparkles/> Você está só no começo: celebre a evolução, divirta-se e continue descobrindo o que pode construir.</small>:null}<div className={styles.modalActions}><button type="button" className={styles.modalShare} onClick={createShareArtwork} disabled={creatingArtwork}>{creatingArtwork?<><LoaderCircle className={styles.spin}/>Criando arte...</>:<><Share2/>Compartilhar resultado</>}</button><button type="button" onClick={()=>{setShowResultModal(false);setTimeout(()=>{resultRef.current?.scrollIntoView({behavior:"smooth",block:"start"});resultRef.current?.focus();},0);}}>Explorar mapa <ArrowRight/></button><button type="button" onClick={restart}><RefreshCcw/>Jogar de novo</button></div></section></div>:null}
    {result&&shareArtwork?<div className={styles.shareBackdrop} role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setShareArtwork(null);}}><section className={styles.shareDialog} role="dialog" aria-modal="true" aria-labelledby="share-art-title"><button type="button" className={styles.modalClose} onClick={()=>setShareArtwork(null)} aria-label="Fechar arte"><X/></button><div className={styles.sharePreview}><img src={shareArtwork.url} alt="Prévia da arte 4 por 5 com o resultado 11RUN"/></div><div className={styles.sharePanel}><span className={styles.eyebrow}>Arte 4:5 · pronta para o Instagram</span><h2 id="share-art-title">Seu resultado virou um card.</h2><p>Compartilhe a imagem e convide seus amigos para descobrir até onde a marca deles pode sonhar.</p><div className={styles.shareCaption}><strong>Legenda sugerida</strong><p>{shareCopy()}</p></div><div className={styles.shareActions}><button type="button" onClick={shareGeneratedArtwork}><Share2/>Compartilhar arte</button><button type="button" onClick={downloadArtwork}><Download/>Baixar JPG 4:5</button></div>{shareStatus?<span role="status">{shareStatus}</span>:null}</div></section></div>:null}
    {result?<section className={styles.results} aria-live="polite"><header><div><span className={styles.eyebrow}>Seu Placar de Potencial</span><h2 ref={resultRef} tabIndex={-1}>{result.analysis.potentialScore===null?"—":`${result.analysis.potentialScore}%`}</h2><strong>{result.narrative.title}</strong><p>{result.narrative.text}</p></div><aside><span>Energia<strong>{result.analysis.confidence}</strong></span><span>Bases exploradas<strong>{result.analysis.comparableSources} de {result.analysis.totalSources}</strong></span><span>Motor<strong>{result.analysis.metadata.engineVersion}</strong></span><span>Atualizado<strong>{new Date(result.analysis.metadata.generatedAt).toLocaleString("pt-BR")}</strong></span></aside></header>
      {result.analysis.badges.length?<section className={styles.achievements}><div><span className={styles.eyebrow}>Conquistas desbloqueadas</span><h3>Seu inventário de jornada.</h3></div><div>{result.analysis.badges.map(badge=>{const Icon=badgeIcons[badge.key]??Star;return <article key={badge.key} data-level={badge.level}><Icon/><span>{badge.level}</span><strong>{badge.label}</strong><p>{badge.description}</p></article>;})}</div></section>:null}
      {result.analysis.youngEndurance.active?<section className={styles.enduranceCare}><HeartPulse/><div><span className={styles.eyebrow}>Distância avançada para a idade</span><h3>Surpresa desbloqueada: uma pequena grande fundista!</h3><p>Correr {result.analysis.youngEndurance.event.toLocaleString("pt-BR")} m tão jovem já demonstra coragem e interesse por distâncias longas. Faça essa aventura sempre com acompanhamento de profissional qualificado, autorização do responsável e atenção a descanso, hidratação e sinais do corpo.</p></div></section>:null}
      <section className={styles.sources}><div><span className={styles.eyebrow}>Sua posição no mundo de hoje</span><h3>Cada fonte preserva sua própria categoria.</h3></div><div className={styles.sourceGrid}>{result.analysis.comparisons.map(source=><article key={source.key}><header><Database/><div><strong>{source.label}</strong><span>{source.category} · {alignmentLabel[source.alignment]}</span></div></header>{source.status==="available"?(source.position?<><b>#{source.position}</b><p>posição hipotética entre {source.count} marcas disponíveis</p><dl><div><dt>Diferença para Top 10</dt><dd>{source.top10GapMs===null?"lista com menos de 10 marcas":source.top10GapMs<=0?"dentro do Top 10":`${(source.top10GapMs/1000).toFixed(2)} s`}</dd></div><div><dt>Atualização</dt><dd>{source.updatedAt?new Date(source.updatedAt).toLocaleDateString("pt-BR"):"não informada"}</dd></div></dl></>:<div className={styles.unavailable}><CircleHelp/><p>Sua marca ficaria além das {source.count} primeiras posições disponíveis nesta base. Nenhuma posição exata foi inventada.</p></div>):<div className={styles.unavailable}><CircleHelp/><p>{source.message??"Esta referência não possui dados sincronizados suficientes."}</p></div>} {source.sourceUrl?<a href={source.sourceUrl}>Abrir ranking usado <ArrowRight/></a>:null}</article>)}</div></section>
      {result.analysis.worldTop50.length?<section className={styles.worldBenchmark}><div><span className={styles.eyebrow}>Régua mundial adulta</span><h3>As 50 marcas que definem o nível de hoje.</h3><p>Uma referência direta e realista para atletas acima de 23 anos. Estar longe desta régua não encerra a jornada: ela mostra com clareza qual é o próximo nível competitivo.</p></div><ol>{result.analysis.worldTop50.map(item=><li key={item.position}><span>#{item.position}</span><strong>{formatDuration(item.performanceMs/1000,true)}</strong></li>)}</ol></section>:null}
      <section className={styles.cycles}><div><span className={styles.eyebrow}>Mapa de fases futuras</span><h3>Quantos ciclos ainda podem entrar no jogo?</h3><p>Cada ciclo é uma nova fase possível para aprender, evoluir e surpreender.</p></div><div>{result.analysis.cycles.map((cycle,index)=><article key={cycle.year}><span>Fase {index+1}</span><Rocket/><strong>{cycle.year}</strong><span>{cycle.age} anos</span></article>)}</div></section>
      {result.analysis.threeKRoutes.length?<section className={styles.routes}><Route/><div><span className={styles.eyebrow}>3.000 m · prova de desenvolvimento</span><h3>Duas rotas olímpicas outdoor de referência.</h3><p>Os 3.000 m rasos não integram diretamente o programa olímpico outdoor adulto. Riegel e Daniels–Gilbert projetam referências para 1.500 m e 5.000 m.</p><div>{result.analysis.threeKRoutes.map(route=><span key={route.distance}><strong>{route.distance.toLocaleString("pt-BR")} m</strong>Riegel {formatDuration(route.riegelSeconds,true)} · VDOT {formatDuration(route.danielsSeconds,true)} · divergência {route.divergencePercent.toFixed(1)}%</span>)}</div></div></section>:null}
      <section className={styles.truth}><Sparkles/><div><span className={styles.eyebrow}>Mensagem da jornada</span><h3>{result.narrative.title}</h3><p>{result.narrative.text}</p></div></section><section className={styles.nextMission}><Rocket/><div><span className={styles.eyebrow}>Próxima missão</span><h3>O jogo continua fora da tela.</h3><p>Cuide da rotina, experimente novas provas e volte quando tiver uma nova marca.</p></div></section><section className={styles.instagramCta}><div><ImageIcon/><span>Card exclusivo 4:5</span><h3>Leve seu placar para o Instagram.</h3><p>Gere uma arte personalizada com seu resultado, sua conquista e um convite para os amigos entrarem no jogo.</p></div><button type="button" onClick={createShareArtwork} disabled={creatingArtwork}>{creatingArtwork?<><LoaderCircle className={styles.spin}/>Criando sua arte...</>:<><Share2/>Criar arte para compartilhar</>}</button></section><footer className={styles.finalActions}><button type="button" onClick={restart}><RefreshCcw/>Analisar de novo</button><button type="button" onClick={share}><Share2/>Indique a um amigo</button><Link href="/meu-painel">Acompanhar evolução <ArrowRight/></Link>{shareStatus?<span role="status">{shareStatus}</span>:null}</footer>
    </section>:null}
  </>;
}
