import type { Metadata } from "next";
import Link from "next/link";
import { ArrowDown, ArrowRight, Route } from "lucide-react";
import { LateStartExperience } from "@/components/LateStartExperience";
import { lateStartFaq } from "@/lib/late-start-content";
import styles from "./page.module.css";

const title="Por que o Brasil começa tarde no fundismo?";
const description="Compare os sistemas de formação de corredores no Brasil, Japão, Estados Unidos, Quênia, Etiópia, Uganda e Noruega e entenda o que significa começar cedo sem antecipar pressão.";
const path="/referencias/analises/o-fundo-comeca-na-infancia";
export const metadata:Metadata={title,description,keywords:["atletismo de base no Brasil","iniciação no fundismo","crianças no atletismo","formação de corredores","especialização esportiva precoce","atletismo escolar","desenvolvimento de atletas","Onze Futuro","11RUN"],alternates:{canonical:path},openGraph:{title:"O problema não é começar tarde a correr. É começar tarde a construir o caminho.",description,type:"article",url:path},twitter:{card:"summary_large_image",title,description}};

export default function LateStartAnalysisPage(){
  const origin=process.env.NEXT_PUBLIC_SITE_URL??"https://11run.com.br";
  const schemas=[{"@context":"https://schema.org","@type":["Article","WebPage"],headline:title,description,datePublished:"2026-08-06",dateModified:"2026-08-06",author:{"@type":"Person",name:"Seiti Katsumi"},publisher:{"@type":"Organization",name:"11RUN",url:origin},mainEntityOfPage:`${origin}${path}`},{"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Início",item:origin},{"@type":"ListItem",position:2,name:"Referências",item:`${origin}/referencias/ranking-brasil`},{"@type":"ListItem",position:3,name:"Análises"},{"@type":"ListItem",position:4,name:title,item:`${origin}${path}`}]},{"@context":"https://schema.org","@type":"FAQPage",mainEntity:lateStartFaq.map(([question,answer])=>({"@type":"Question",name:question,acceptedAnswer:{"@type":"Answer",text:answer}}))}];
  return <article className={styles.page}>{schemas.map((schema,index)=><script key={index} type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,"\\u003c")}}/>)}<nav className={styles.breadcrumb} aria-label="Trilha de navegação"><Link href="/">Início</Link><span>/</span><Link href="/referencias/ranking-brasil">Referências</Link><span>/</span><strong>Análises</strong><span>/</span><b>O fundo começa na infância?</b></nav><header className={styles.hero}><div><span className={styles.eyebrow}>Análises 11RUN · Formação de corredores</span><h1>O fundo começa na infância?<em>O caminho, sim.</em></h1><p>O Brasil não precisa antecipar pressão. Precisa começar antes a construir movimento, acesso, repertório e continuidade.</p><div className={styles.actions}><a href="#pergunta">Começar a análise <ArrowDown/></a><a href="#mundo">Comparar os países <Route/></a><Link href="/onze-futuro">Conhecer o Onze Futuro <ArrowRight/></Link></div><small>Infância protegida · Atletismo escolar · Desenvolvimento · Sistemas esportivos</small></div><aside aria-label="Síntese visual do caminho esportivo"><span>Movimento</span><i/><span>Experiência</span><i/><span>Continuidade</span><i/><strong>Múltiplos futuros</strong><p>Sem selecionar cedo demais.</p></aside></header><nav className={styles.jumpNav} aria-label="Nesta análise">{[["A pergunta","pergunta"],["Ciência","ciencia"],["Três começos","comecos"],["O mundo","mundo"],["Brasil","brasil"],["Escola","escola"],["Ecossistema","ecossistema"],["Onze Futuro","onze-futuro"],["Evidências","evidencias"],["Fontes","fontes"],["Dúvidas","duvidas"]].map(([label,id])=><a key={id} href={`#${id}`}>{label}</a>)}</nav><LateStartExperience/><section className={styles.signature}><div><span className={styles.eyebrow}>Análises 11RUN</span><h2>O talento não precisa aparecer cedo. O caminho precisa.</h2><p>Acesso, proteção e continuidade mantêm mais possibilidades abertas para cada criança.</p></div><div><strong>Seiti Katsumi</strong><span>Fundador da 11RUN</span></div></section></article>;
}
